### ISSUE TITLE
Ungoogled Chromium

### ISSUE THREAD

**Issue by calhix** [AsahiLinux/linux#100]
Been trying to get this to work for a while now. I have an issue for the flatpak here: https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/84 where I'm getting some GPU errors for both the vanilla chromium and ungoogled-chromium flatpak. Vanilla Chromium works fine from the AUR with no changes needed. I couldn't get ungoogled-chromium to build but I could get ungoogled-chromium-bin to build (all I did was change x86_64 to aarch64). When trying to open in the terminal, I get:

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:16384 Cores:8
Box64 with Dynarec v0.2.0 93fde45 built on Nov 29 2022 06:48:59
Error: PageSize configuation is wrong: configured with 4096, but got 16384

I found this issue which is similar but can't seem to figure out how to make it work for ungoogled-chromium-bin: ptitSeb/box64#279

**Comment by marcan** [comment]
This is not a kernel issue, and I have no idea what you're trying to do here (run an x86-64 version of Chromium with box64? what?).

Chromium works fine and I expect proper ARM64 builds of Ungoogled Chromium would work fine too. If you expect Chromium-on-box64 to work and it doesn't, please report that as a box64 bug.

Additionally, do not expect Flatpak anything to work with GPU acceleration at this time, as Flatpak cannot use the system's GPU drivers due to its design.

**Comment by calhix** [comment]
I know I should have replied earlier but better late than never, this is just the error I got when building ungoogled-chromium-bin from the AUR and only changing arch=('x86_64') to arch=('aarch64') in the PKGBUILD. The error threw me off too but you're right that vanilla Chromium works fine but the reason I started this is because the ARM build of ungoogled-chromium works fine on the PinePhone/PPP so I was thinking this may be the proper place as it may help with troubleshooting. Thank you anyway.

**Comment by wxllow** [comment]
> I know I should have replied earlier but better late than never, this is just the error I got when building ungoogled-chromium-bin from the AUR and only changing arch=('x86_64') to arch=('aarch64') in the PKGBUILD. The error threw me off too but you're right that vanilla Chromium works fine but the reason I started this is because the ARM build of ungoogled-chromium works fine on the PinePhone/PPP so I was thinking this may be the proper place as it may help with troubleshooting. Thank you anyway.

`ungoogled-chromium-bin` doesn't work because it only has a source for x86_64, which is why the package has its architecture marked as such. You need to find somewhere with an ARM build of ungoogled-chromium or build it yourself
