### ISSUE TITLE
LCD Backlight goes black after booting the edge kernel

### ISSUE THREAD

**Issue by derzahla** [AsahiLinux/linux#104]
I was so happy to have a beautifully working backlight and encouraging GPU support using the latest edge kernel.   It worked for about a day.    I rebooted to test a custom kernel and ever since that, the backlight no longer works at all on the edge kernel.  It works in binary mode on the default kernel just fine, but as soon as the edge kernel boots the backlight shuts off, leaving the screen very dark and difficult to make out.  f1/f2 keys have no effect. /sys/class/backlight directory is empty.  logs indicate that the systemd-backlight service isnt running, but that service doesnt exist. 

I have tried reinstalling the edge kernel to make sure all the proper hooks were rerun but no luck.  I have posted in the IRC channel as well but no one has been able to help so far.  Creating this bug to document it, I hope this is the proper place for it.  Please advise.

Note: asahi-diagnose output has been uploaded here: https://pastebin.com/avTF7qww

Thanks!

**Comment by marcan** [comment]
`/sys/class/backlight` being empty confuses me. Are you sure about that?

All I can think of is that you've ended up with some bad device trees. Are there any directories matching `/lib/modules/*-ARCH` that are *not* the two official kernels? If so, remove them and run `update-m1n1`.

**Comment by derzahla** [comment]
```[root@tyr ~]# uname -a
Linux tyr 6.1.0-asahi-2-2-edge-ARCH #2 SMP PREEMPT_DYNAMIC Fri, 16 Dec 2022 05:04:23 +0000 aarch64 GNU/Linux
[root@tyr ~]# ls -lah /sys/class/backlight/
total 0
drwxr-xr-x  2 root root 0 Dec 31  1969 .
drwxr-xr-x 61 root root 0 Dec 31  1969 ..
[root@tyr ~]# ls -lah /lib/modules
total 0
drwxr-xr-x 1 root root   90 Jan 20 12:32 .
drwxr-xr-x 1 root root 188K Jan 20 12:26 ..
drwxr-xr-x 1 root root  488 Jan 12 12:13 6.1.0-asahi-2-2-ARCH
drwxr-xr-x 1 root root  478 Jan 12 12:13 6.1.0-asahi-2-2-edge-ARCH
[root@tyr ~]# update-m1n1 
Reading m1n1 config from /etc/m1n1.conf:
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
Mounted System ESP /dev/nvme0n1p4 at /run/.system-efi
m1n1 updated at /run/.system-efi/m1n1/boot.bin
[root@tyr ~]# systemctl daemon-reload 
[root@tyr ~]# update-m1n1 
Reading m1n1 config from /etc/m1n1.conf:
Mounted System ESP /dev/nvme0n1p4 at /run/.system-efi
m1n1 updated at /run/.system-efi/m1n1/boot.bin
[root@tyr ~]# reboot
[root@tyr ~]# Connection to tyr closed by remote host.
Connection to tyr closed.
```

Well that seemed to do the trick!  I never ran update-m1n1 manually since i thought it was being run by the pacman hooks whenever i would do a 'pacman -S linux-asahi-edge' to reinstall the kernels.   Thanks!
