### ISSUE TITLE
Custom distro : winesapOS

### ISSUE THREAD

**Issue by MikNewCal** [AsahiLinux/linux#113]
Hi all

I was wondering if we could install winesapOS (https://github.com/LukeShortCloud/winesapOS) over AsahiLinux or separately

I tried to put the iso image on a usb key and to boot on it with bootloader but without success

" Is winesapOS a Linux distribution?
Yes. We provide customized packages, a package repository, various optimizations, and our own upgrade process. winesapOS is a fork of SteamOS 3 (which is a fork of Arch Linux). "

**Comment by RigoLigoRLC** [comment]
Look at the minimum system requirements of winesapOS. It says Intel/AMD
processor. And I doubt it would support Apple Silicon at all in the future
since SteamOS is basically completely x86 based.

MikNewCal ***@***.***> 于 2023年2月25日周六 上午8:08写道：
