### ISSUE TITLE
6.1.0 - single occurence of non-working keyboard/mouse

### ISSUE THREAD

**Issue by SjonHortensius** [AsahiLinux/linux#115]
I have been running this kernel on my `Apple MacBook Air (13-inch, M2, 2022` just fine, and it is working again now. I just experienced a weird issue where my mouse and keyboard didn't work, but the power-key still did fortunately, allowing me to reboot. I found the following message:

```
apple-dart 231304000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 1] initialized
apple-dart 23130c000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 1] initialized
apple-dart 24e808000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-dart 382f00000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-dart 382f80000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-dart 502f00000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-dart 502f80000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-gpio-pinctrl 23c100000.pinctrl: No cache defaults, reading back from HW
apple-dart 681008000.iommu: DART [pagesize 4000, 16 streams, bypass support: 0, bypass forced: 0, locked: 0] initialized
```

```
Unable to handle kernel NULL pointer dereference at virtual address 0000000000000040
Mem abort info:
  ESR = 0x0000000096000044
  EC = 0x25: DABT (current EL), IL = 32 bits
  SET = 0, FnV = 0
  EA = 0, S1PTW = 0
  FSC = 0x04: level 0 translation fault
Data abort info:
  ISV = 0, ISS = 0x00000044
  CM = 0, WnR = 1
user pgtable: 16k pages, 48-bit VAs, pgdp=000000081194b670
[0000000000000040] pgd=0000000000000000, p4d=0000000000000000
Internal error: Oops: 0000000096000044 [#1] PREEMPT SMP
apple-gpio-pinctrl 24a820000.pinctrl: No cache defaults, reading back from HW
Modules linked in: pcie_apple(+) phy_apple_atc dwc3 pci_host_common udc_core typec apple_dockchannel apple_rtkit_helper(+) rtc_macsmc spmi_apple_controller nvmem_apple_efuses pinctrl_apple_gpio i2c_apple apple_dart nvme_apple apple_sart
CPU: 3 PID: 271 Comm: (udev-worker) Tainted: G S                 6.1.0-asahi-2-2-ARCH #1
Hardware name: Apple MacBook Air (13-inch, M2, 2022) (DT)
pstate: 60400009 (nZCv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
pc : apple_dart_of_xlate+0x4c/0x1a4 [apple_dart]
lr : apple_dart_of_xlate+0x120/0x1a4 [apple_dart]
sp : ffff80000a0e3860
x29: ffff80000a0e3860 x28: ffff800000cb8100 x27: ffff80000a0e3d80
x26: 0000000000000000 x25: 0000000000000000 x24: ffff800008ea9c58
x23: ffff800008ea9c68 x22: ffff000013b4e080 x21: ffff00000e3d5c10
x20: ffff00001536a100 x19: 0000000000000001 x18: ffffffffffffffff
x17: 0000000000000000 x16: 0000000000000000 x15: ffffffffffffffff
x14: ffff00001536968a x13: ffff000015369688 x12: 622e756e672e6574
x11: 0000000000000000 x10: ffff81000b2dad24 x9 : 0000000000000000
x8 : ffff00001536a180 x7 : 0000000000000000 x6 : 000000000000003f
x5 : 0000000000000040 x4 : ffff80000a0e3840 x3 : 0000000000000000
x2 : 0000000000000000 x1 : ffff000015667c00 x0 : 0000000000000000
Call trace:
 apple_dart_of_xlate+0x4c/0x1a4 [apple_dart]
 of_iommu_xlate+0xa4/0xe0
 of_iommu_configure+0x170/0x1e0
 of_dma_configure_id+0x12c/0x330
 platform_dma_configure+0x30/0x80
 really_probe+0x74/0x3dc
 __driver_probe_device+0x7c/0x190
 driver_probe_device+0x3c/0x110
 __driver_attach+0xf4/0x1f0
 bus_for_each_dev+0x70/0xd0
 driver_attach+0x24/0x30
 bus_add_driver+0x17c/0x240
 driver_register+0x78/0x130
 __platform_driver_register+0x28/0x34
 apple_rtkit_helper_driver_init+0x20/0x4000 [apple_rtkit_helper]
 do_one_initcall+0x50/0x1bc
 do_init_module+0x70/0x200
 load_module+0x954/0xa84
 __do_sys_finit_module+0xac/0x130
 __arm64_sys_finit_module+0x20/0x30
 invoke_syscall.constprop.0+0x50/0xf0
 do_el0_svc+0x4c/0xe0
 el0_svc+0x30/0x120
 el0t_64_sync_handler+0xf4/0x120
 el0t_64_sync+0x18c/0x190
Code: 540002c1 b9400e73 b4000654 f94156a0 (f9002014) 
---[ end trace 0000000000000000 ]---
```

```
apple-dart 235004000.iommu: DART [pagesize 4000, 16 streams, bypass support: 1, bypass forced: 0, locked: 0] initialized
apple-gpio-pinctrl 23d1f0000.pinctrl: No cache defaults, reading back from HW
apple-gpio-pinctrl 23e820000.pinctrl: No cache defaults, reading back from HW
pcie-apple 690000000.pcie: host bridge /soc/pcie@690000000 ranges:
pcie-apple 690000000.pcie:      MEM 0x06a0000000..0x06bfffffff -> 0x06a0000000
pcie-apple 690000000.pcie:      MEM 0x06c0000000..0x06ffffffff -> 0x00c0000000
```

**Comment by marcwimmer** [comment]
hi,
we experience this all every 15th to 20th boot; error -19 and no
mouse/keyboard.
trying some reboots and then it works.


Am Mi., 1. März 2023 um 18:21 Uhr schrieb SjonHortensius <
***@***.***>:

**Comment by antony** [comment]
I'm experiencing the same thing after upgrading to this latest kernel version. However I'm simply unable to log in, no matter how much rebooting I do. No mouse, no keyboard, and after 10 seconds the cursor stops blinking (Assume the machine froze at this point)

Macbook Pro 2020 M1

**Comment by marvstod** [comment]
On a MacBooK Pro M2, an install of Ubunutu 23.10 was done.  When the Ubunutu logon screen was first raised, neither mouse nor keyboard were functional.  There was function through the USB-C ports.  But the two USB-C ports are too closely spaced to simultaneously fit two  USB-C to USB-A adapters, needed to at once support USB-A mouse and keyboard.  Having a 4-Port USB dongle, concurrent support of external mouse and keyboard was achieved through a reboot.  Login was thus accomplished with follow through Oct 10 software update.  Upon reboot without dongle, there was functionality of mouse, keyboard and wireless functions.  

To prevent this mouse/keyboard hardship in future installs, pre-logon support of mouse and keyboard should be implemented soon.

Less severe issuses:
Sound is only through USB-C earbuds, though haven't yet tested  Bluetooth sound devices;
the fancy forward Touchbar for Sound and Brightness is not yet functional.

**Comment by jannau** [comment]
@marvstod please do not recycle old issues.

> On a MacBooK Pro M2, an install of Ubunutu 23.10 was done. When the Ubunutu logon screen was first raised, neither mouse nor keyboard were functional.

> To prevent this mouse/keyboard hardship in future installs, pre-logon support of mouse and keyboard should be implemented soon.

This is an [UbuntuAsahi](https://github.com/UbuntuAsahi) specific issue and works on Fedora-Asahi-Remix and the alarm based distro without problems, please report it there.

> Less severe issuses: Sound is only through USB-C earbuds, though haven't yet tested Bluetooth sound devices; the fancy forward Touchbar for Sound and Brightness is not yet functional.

Please do not report several unrelated issues in a single port. Also please do not report missing features as issues although the headphone jack should work and the touchbar works in Fedora-Asahi-Remix.

**Comment by marcan** [comment]
This issue seems to have collected a mess of unrelated reports (e.g. trackpad on M1 and M2 are completely unrelated drivers). If anyone is still experiencing similar issues on Fedora or Arch, please open another issue and attach an asahi-diagnose log. Issues with other distros should be directed at their developers.
