### ISSUE TITLE
How do i install this version?

### ISSUE THREAD

**Issue by ImUltik** [AsahiLinux/linux#116]
if anyone knows tell me thx

**Comment by src52** [comment]
You need to be much more specific if you actually want people to help you.

The issue tracker isn't a public forum for you to ask extremely basic questions that could easily be answered if you spent 5 seconds doing your own research. You're a smart person, use the internet and find out how to install Asahi Linux. Using a search engine works wonders, believe it or not.

Don't waste people's time by posting vague nonsense, hoping someone will spoon-feed you.
