### ISSUE TITLE
Chromium skia shader compilation error

### ISSUE THREAD

**Issue by activaigor** [AsahiLinux/linux#120]
after the latest updates all chromium based browsers stopped to render some of the text (some fonts are visible though)
i can see this error happening a lot
```
Errors:
0:1(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
0:2(12): warning: extension `GL_EXT_gpu_shader5' unsupported in fragment shader
0:3(1): error: `out' qualifier in declaration of `webgl_SecondaryFragColor' only valid for function parameters in GLSL 1.10
0:0(0): error: fragment shader writes to both `gl_FragColor' and `webgl_SecondaryFragColor'

[9135:9135:0320/193751.712570:ERROR:shared_context_state.cc(77)] Skia shader compilation error
```
![image](https://user-images.githubusercontent.com/8046594/226423655-58819811-84b3-4a74-83b8-3780580ad86c.png)

**Comment by jannau** [comment]
Please update again, should be fixed. See https://social.treehouse.systems/@AsahiLinux/110056919827415091

**Comment by activaigor** [comment]
perfect! thank you guys!
