### ISSUE TITLE
Screen does not extend to the top portion of the display (M2 Macbook Air)

### ISSUE THREAD

**Issue by System64fumo** [AsahiLinux/linux#121]
The screen doesn't utilize the extra pixels where the notch is leaving a black bar.
There also doesn't seem to be any other supported display modes other than 2560x1600.
cat /sys/class/drm/card2-eDP-1/modes
2560x1600

In theory supporting a resolution of 2560x1664 should fix this, But judging by the fact that the screen is not
vertically centered i assume that it's more complicated than that.

 host     Apple MacBook Air (13-inch, M2, 2022)
 kernel 6.2.0-asahi-11-1-edge-ARCH

**Comment by jannau** [comment]
The region partially occluded by the notch is intentionally omitted. Offering a mode which includes those extra 64/72 lines requires at least a way to report the occluded regions to user space. We might want to wait until there is work on compositors to support partially occluded displays.

**Comment by System64fumo** [comment]
Is there any particular reason behind the requirement or is it just so the end user doesn't have content blocked off on their screen?

**Comment by DavidBuchanan314** [comment]
It would be nice to have the notched resolution available as an option, even if it's not enabled by default.

For example, moving the task bar to the top of the screen allows for a pretty decent user experience, even without software being aware of the notch.

**Comment by System64fumo** [comment]
Adding apple_dcp.show_notch=1 to the kernel parameters seems to fix this.
