### ISSUE TITLE
Visual glitches when using blur on a wlroots based compositor

### ISSUE THREAD

**Issue by System64fumo** [AsahiLinux/linux#122]
Visual glitches appear when using a blur effect on a wlroots based compositor.
These glitches do not appear when using kwin but do appear when using wayfire or hyprland.
Visual glitches typically consist of repeated content but can also have weird purple glow around windows.

Hyprland:
![20230323_02h22m12s_grim](https://user-images.githubusercontent.com/72354122/227067940-d8901819-1dc6-4701-a40d-e5469a69fa28.png)

Wayfire:
![20230323_02h21m06s_grim](https://user-images.githubusercontent.com/72354122/227067980-0a59d332-13f9-47ce-970a-a7f2685d5727.png)

host  Apple MacBook Air (13-inch, M2, 2022)
kernel 6.2.0-asahi-11-1-edge-ARCH

**Comment by marcan** [comment]
Does this still happen with the latest packages?

**Comment by System64fumo** [comment]
Nope, Seems to be fixed with the latest opengl 3 update.
Thanks!
