### ISSUE TITLE
When the system is woken from sleep, this occasionally happens.  

### ISSUE THREAD

**Issue by SamilKaraduman** [AsahiLinux/linux#144]
![Screenshot_20230508_213502](https://user-images.githubusercontent.com/83664323/236971971-0ea8242b-e927-4b1a-bc40-2133d8b229d5.png)

[asahi-diagnose-20230508-213338.txt](https://github.com/AsahiLinux/linux/files/11426374/asahi-diagnose-20230508-213338.txt)

Don't know if this specific to ALARM issue, but I have not experienced something like this in other distros I have tested on this machine, (although I have experienced something like this similar on Ubuntu.) Happens at least once a day and slows down my workflow by a huge margin. 

OS: Alarm (Minimal from installer, installed Plasma)
Host: MBA (M1, 2020)

I really don't want to move back to Fedora, as I was experiencing a slow app launch issue. Maybe once that is resolved I will make the switch over to Fedora when it is added to the installer.

**Comment by marcan** [comment]
Does this still happen?

**Comment by SamilKaraduman** [comment]
After the update, no it doesn't. Forgot about this issue. Thanks for everything you do!
