### ISSUE TITLE
Unusual battery drain overnight

### ISSUE THREAD

**Issue by DaveFlashNL** [AsahiLinux/linux#145]
![IMG_4687](https://user-images.githubusercontent.com/72280178/237055366-7fbc1f40-7806-4b48-9d36-44c362957291.jpeg)

sorry for the bad photo, but my macbook drained overnight on Asahi Linux, even though i fully charged it yesterday,
i've never seen this happen under any OS, not under Big Sir, Monterey or Ventura, and I dual b- no quadruple boot all of them on this macbook (+Asahi). this is so weird and frustrating. I've never let this battery deplete like this. this is bad

**Comment by shinomax** [comment]
Because of cpu usage, i don't know how but my cpu always higher and warmer even though i don't running any app (20% cpu).

**Comment by DaveFlashNL** [comment]
> Because of cpu usage, i don't know how but my cpu always higher and warmer even though i don't running any app (20% cpu).

yes yes indeed! I noticed it again, my macbook was in my bag and it was hot or mildly warm when it was closed and with Asahi running, i've never had it when it was sleeping with macOS active on it. This is a serious design flaw of Asahi. If on desktop Apple Silicon, this would not be an issue ofc, but I'm on a laptop. this needs to be solved asap.

**Comment by marcan** [comment]
Improved idle power management is an ongoing work in progress and involves lots of different parts and drivers. This isn't something that can be "solved asap". Many x86 laptops have even worse sleep power draw. We're working on it, but please don't open issues for it. It will be a long, long time before we can match macOS' weeks of sleep time.

If you are seeing high CPU usage, make sure you have the GPU drivers installed. If it still happens, you'll have to look through your process list and figure out the culprit yourself. This is not a platform issue, we can't help you if you have some random Linux app eating CPU.
