### ISSUE TITLE
How to enable BPF-related kernel features

### ISSUE THREAD

**Issue by wqld** [AsahiLinux/linux#146]
M1 Mac Mini

```shell
$ uname -a
Linux wq-asahi 6.1.0-rc6-asahi-4-1-ARCH #1 SMP PREEMPT_DYNAMIC Tue, 22 Nov 2022 06:06:17 +0000 aarch64 GNU/Linux
```

## Description

I tried to run the script `/bpftrace/scripts/check_kernel_features.sh` to use the bpftrace tool, and I get the following message.

```shell
$ ./Workspace/bpftrace/scripts/check_kernel_features.sh 
Required option CONFIG_BPF_EVENTS not set
Required option CONFIG_FTRACE_SYSCALLS not set
Required option CONFIG_FUNCTION_TRACER not set
Required option CONFIG_DYNAMIC_FTRACE not set
Required option CONFIG_KPROBE_EVENTS not set
Required option CONFIG_UPROBES not set
Required option CONFIG_UPROBE_EVENTS not set
Missing required features
```

I tried to build the source code and install it, but it didn't work, maybe I'm just inexperienced...
Is there an easy way to set this up during the Asahi Linux installation process, or how do I enable this feature?
Can I use bpftrace on asahi linux..?

**Comment by 21kyu** [comment]
I think I can use PKGBUILDs, is that correct?

**Comment by wqld** [comment]
I think I can use PKGBUILDs to change the config, is that correct?

**Comment by wqld** [comment]
I successfully enabled the above configs and passed the `./check_kernel_features.sh`, but I'm still getting various issues when I try to use `bpftrace`. (BTF, tracepoint, etc…)

**Comment by wqld** [comment]
I checked with menuconfig and there was a config that wasn't enabled (dependency).
I enabled them all and applied them and it works fine.
