### ISSUE TITLE
No sound (from headphone jack)

### ISSUE THREAD

**Issue by mbrennwa** [AsahiLinux/linux#147]
There is no sound output from the headphone jacks with my Asahi installation:

- MacBook Air M2
- Installed Asahi with Debian as described [here](https://git.zerfleddert.de/cgi-bin/gitweb.cgi/m1-debian)  (tldr: `curl -sL https://tg.st/d | sh`)
- Kernel version: `6.3.0-asahi-00538-g3965d153b13f`
- The headphone jack is recognized by Gnome Sound Settings, which changes from "Speakers - Built-in Audio" to "Headphones - Built-in Audio" when the headphones are plugged in.
- I tried to get sound from the Gnome Sound Settings "Test" button and from a webbrowser (with Youtube etc.), but the headphones remained silent.
- The headphone output works on macOS and with the Asahi/KDE install (`curl https://alx.sh | sh`).

What am I missing?

**Comment by jannau** [comment]
`Speakers - Built-in Audio` is surprising but that seems to be a Gnome thing. My best guess is either a wrong mixer setting (try to check with `alsamixer -c 0`) or missing asahi specific alsa UCM config (maybe called "alsa-ucm-conf-asahi").

Apart from this rather general tips we don't know either. Please ask the provider of the debian install.

**Comment by mbrennwa** [comment]
I tried `alsamixer -c 0`. The command worked and showed some audio stuff, but I did not know / understand what to look for.

`alsa-ucm-conf-asahi` does not seem to exist:
```
apt install alsa-ucm-conf-asahi
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package alsa-ucm-conf-asahi
```

Digging deeper, I can see `alsa-ucm-conf`, which is already installed but does not have `asahi` in the name:
```
apt-cache search --names-only alsa-ucm
alsa-ucm-conf - ALSA Use Case Manager configuration files
```

**Comment by mbrennwa** [comment]
Sound output from the headphone jack now works. I simply copied the files in https://github.com/AsahiLinux/alsa-ucm-conf-asahi/tree/master/ucm2/conf.d/macaudio to `/usr/share/alsa/ucm2/conf.d/macaudio/` (had to create the `macaudio` directory first). After a reboot, sound was on!

I am sure there is a cleaner way to achieve this, maybe using a deb package. I have no clue how to do this, but maybe someone can point me in the right direction.

**Comment by marcan** [comment]
This looks like a Debian packaging issue, unrelated to the kernel.
