### ISSUE TITLE
Print "this software is made with love by a queer transgender person" somewhere in dmesg

### ISSUE THREAD

**Issue by SoniEx2** [AsahiLinux/linux#149]
doesn't really matter where - kernel hello, GPU drivers, whatever.

if this software becomes illegal over it at some point, then we want to see microsoft/github held to fighting back to protect this software (or they'll be exposed as a problem). but the main short-term use-case is to weed out ppl who wanna get themselves banned from the community.

**Comment by KaffeinatedKat** [comment]
I think going out of your way to find people to ban is like solving a problem that doesn't exist. Overall does nothing, it doesn't improve the project at all. If anything you might be banning people who could actually improve the project. You're going to need a better reason than "weeding out ppl who wanna get themselves banned"

**Comment by idkso** [comment]
> doesn't really matter where - kernel hello, GPU drivers, whatever.
> 
> if this software becomes illegal over it at some point, then we want to see microsoft/github held to fighting back to protect this software (or they'll be exposed as a problem). but the main short-term use-case is to weed out ppl who wanna get themselves banned from the community.

umm if it ever becomes illegal people can just violate the license anyways 🤓

**Comment by marcan** [comment]
Discussed on IRC why this isn't necessarily a good idea.

Notwithstanding that, people who would hypothetically take direct offense at such a statement are not, in fact, welcome in our community, and will be shown the door if they express such views.
