### ISSUE TITLE
M2 PMU does not seem to fully work with M1 events

### ISSUE THREAD

**Issue by sidkshatriya** [AsahiLinux/linux#150]
I'm trying to get the `rr` debugger to work on the M2.

The good news is that the PMU seems to work fine as asahi for M2 can simply use the M1 events. So if we do something like this on the M2: 

```bash
# run the `true` command and see how many raw events 0x90 are generated: 
$ sudo perf stat --cpu=5 -e r90:u true
# or equivalently
$ sudo perf stat --cpu=5 -e apple_avalanche_pmu/r90/u true
```

This works great and events are counted on the M2 ! (Event 0x90 is used in rr for M1). We get something like this:

```
 Performance counter stats for 'CPU(s) 5':

               240      apple_avalanche_pmu/r90/u                                             

       0.000405876 seconds time elapsed
```

The next part is that we want to be able to set a period on PMU event 0x90, and ask linux to send a signal to a thread after a certain number of events are executed by a thread. 

If `fd` corresponds to the file descriptor for PMU counter for event 0x90, this can be done via something like:

```c
...
// Sent a signal `some_signal_num` to the thread `some_thread_id`
// when `some_period` events are seen
struct f_owner_ex target;
target.type = F_OWNER_TID;
some_thread_id = 1234;
target.pid = some_thread_id;
fcntl(fd, F_SETOWN_EX, &target)
fcntl(fd, F_SETFL, O_ASYNC);
fcntl(fd, F_SETSIG, some_signal_num);
// Set a period `some_period` and enable it on the counter
some_period = 456;
ioctl(fd, PERF_EVENT_IOC_PERIOD, &some_period);
ioctl(fd, PERF_EVENT_IOC_ENABLE, 0);
...
```

(This is an extremely simplified version of what happens in https://github.com/rr-debugger/rr/blob/32167ae8b4b2c66c4d81aa38873fbf4a11f12059/src/PerfCounters.cc#L620 )

Now based on my testing, it seems that the M2 PMU is *not* able to trigger the signal after a certain number of events are seen. 

I've tried to look at the code here: https://github.com/AsahiLinux/linux/blob/a189eadd37058cf4dd958d1861bc0bf09f21eea9/drivers/perf/apple_m1_cpu_pmu.c and I'm guessing it has to do with the IRQ stuff but I don't know enough to figure out what may be wrong.

**Comment by sidkshatriya** [comment]
cc: @yuyichao who wrote a lot of the rr on aarch64 support (and added M1 support)

Also cc: @marcan who might know who might be the best to ping on PMU stuff on M1/M2... 

(Thanks in advance !)

**Comment by yuyichao** [comment]
Have you tried pinning the thread to a single core? The Linux kernel refuses to provide any support for combining events count in kernel so your code can only count either the big or the small core pmu depending on how you set it up. If your code got migrated between core the event might stops firing because of that.


as a side note, somehow I cant see any pmu events anymore on my m1 recently and I’m not sure why…

**Comment by sidkshatriya** [comment]
> Have you tried pinning the thread to a single core? 

If you mean using `--bind-to-cpu`, that does not seem to help. The issue seems to lie with the kernel not issuing a signal after a particular number of events are seen (as described above).

> as a side note, somehow I cant see any pmu events anymore on my m1 recently and I’m not sure why…

Sorry I don't have an M1 so can't debug the issue. I'm using the `linux-asahi-edge` kernel. Could you try switching to it in case you're not using it? Alternatively shift back to `linux-asahi` (if you're on `linux-asahi-edge`) and see if it makes a difference for the M1 ? 

P.S. Please check the WIP PR https://github.com/rr-debugger/rr/pull/3528 for M2 support

**Comment by jannau** [comment]
@sidkshatriya , I don't see any PMU interrupts on M2 (`grep pmu /proc/interrupts`) with "6.2.0-asahi-12-edge" when using `perf record -F max ...` which should have a similar usage. I'm sure I tested that so we appear to have broken that.

@yuyichao, I do not see any problems with [asahi-wip](https://github.com/AsahiLinux/linux/tree/asahi-wip) (6.3 based) on M1 Max

**Comment by sidkshatriya** [comment]
This is what I see on `6.2.0-asahi-11-1-edge` on M2 -- is there still something missing?
```
$ grep pmu /proc/interrupts
 49:          0          0          0          0          0          0          0          0   AIC-FIQ   4 Level     arm-pmu
 50:          0          0          0          0          0          0          0          0   AIC-FIQ   5 Level     arm-pmu
```

**Comment by sidkshatriya** [comment]
Now:
```
$ cat /sys/bus/event_source/devices/apple_avalanche_pmu/type
7
$ cat /sys/bus/event_source/devices/apple_blizzard_pmu/type
6
```

What we see above is 4 and 5 only. Is that what we're looking for?

**Comment by yuyichao** [comment]
I'm pretty sure the 6 and 7 you see in the pmu type are simply the two number after `PERF_TYPE_BREAKPOINT` and are specific to the perf event user API. I'll be a little surprised if it has anything to do with the `/proc/interrupts` numbers thought that's just my guess.

**Comment by sidkshatriya** [comment]
@jannau Sorry for the ping -- I'm eager to figure out how I should proceed / what may be wrong ! :-) 

Regarding pmu related interrupts on the M2 -- what should I be seeing in https://github.com/AsahiLinux/linux/issues/150#issuecomment-1563416007 ?

**Comment by sidkshatriya** [comment]
>  perf record -F max ... 

Indeed using e.g. `sudo perf record --cpu=5 -F max -e r90:u -- <some long running command>` gives a suspicious output on M2.

```
info: Using a maximum frequency rate of 1,00,000 Hz
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 1.896 MB perf.data ]
```

OTOH doing something with a counter e.g. on Intel machines
- You will get more than 1 wakeup. M2 suspiciously always returns a single wakeup.
- You will often get thousands samples. Here perf does not even report a single sample for M2 ! This seems to be the case on M2 always

**Comment by sidkshatriya** [comment]
Resolved -- Fixed.

M2 PMU issues interrupts after applying kernel patch by Marc Zyngier at https://lists.infradead.org/pipermail/linux-arm-kernel/2023-May/837374.html
