### ISSUE TITLE
`cargo install alacritty` reliably crashes `asahi-dev` 6.3.0-asahi-3-1 kernels

### ISSUE THREAD

**Issue by sidkshatriya** [AsahiLinux/linux#152]
I'm using the very recently released 6.3.0-asahi-3-1 kernel on the `asahi-dev` repo.

I'm reliably able to crash my M2 running Asahi Linux (Arch linux) by simply invoking:

```bash
$ cargo install alacritty
```

This happens regardless of whether I am using:
- an edge or non-edge kernel
- whether I'm in X11 or wayland or a plain tty (via `Ctrl+Alt+Fn<num>` )

Basically somewhere towards the end of the compilation my M2 will reboot without showing any panic or anything on the screen. I also am _not_ able to see anything relating to this problem after the reboot in the system journal (`journalctl -b -1`). 

It seems that the error is so fatal that linux does not have time to log what happened !

**Comment by sidkshatriya** [comment]
(I'm using rustc `1.69.0` installed via rustup )

**Comment by jannau** [comment]
Does this happen on a M2 Macbook Air? Not reproducible on a Macbook Pro 13" M2

**Comment by sidkshatriya** [comment]
Yes, this happens on an M2 Macbook Air...

**Comment by 1ace** [comment]
@sidkshatriya are you doing that with the power cable plugged in?  I'm getting the exact same issue you're describing when it's not plugged in, and @marcan just suggested trying with it plugged in, and I could compile just fine. It would be great if you can confirm it's the same thing for you

**Comment by cyrinux** [comment]
Hi, I can confirm too the crash on M2 air when building alacritty (but I suppose its just a way of getting quickly cpu load?), with last asahi-dev stuff (kernel 6.3.0-asahi-4-1-edge-ARCH)
This happen without AND with power plugged in. 

I can have the same kind of crash with playing supertuxkart sometimes, it happen often but never at the same moment. Sometimes I can play without problem when I click to exit the game, it freeze, then panic/reboot.
I don't have a second laptop sadly to get kernel log during the crashes sadly.

**Comment by sidkshatriya** [comment]
This problem seems to be resolved after updating to m1n1 version `1.2.9-2` on the `asahi-dev` stream. 

Now M2 air does not reboot -- whether plugged in or not when compiling alacritty. 

To further load the system, I also tried building alacritty with linux compiling with -j8 in the background -- that too did not result in a reboot. Seems like this problem has been resolved :+1: 

cc: @marcan

**Comment by cyrinux** [comment]
I confirm, this looks ok for me too now on my m2 air.
