### ISSUE TITLE
AsahiLinux does not boot with attached external SSD NVM USB-C drive

### ISSUE THREAD

**Issue by hackgrid** [AsahiLinux/linux#154]
Hi,

when I start AsahiLinux on my MacBook Air M1 (2020) while my Samsung T7 2TB external SSD NVM drive is plugged in, it won't boot - instead if will reboot and start MacOSX.

I see Uboot, and it checks something on this USB drive, but then it reboots immediately.

Unfortunately I dont know which log file to check for messages, so if you could provide me a file path I can give you more details!

Thanks and kind regards! :)

**Comment by marcan** [comment]
Is your system up to date? A whole pile of u-boot USB fixes went in recently.

**Comment by hackgrid** [comment]
Updated as of 2023.06.10.
I will try again later, thanks!

Hector Martin ***@***.***> schrieb am Do., 15. Juni 2023,
21:32:

**Comment by hackgrid** [comment]
I updated now, only 3 linux-edge and mesa-edge packages were updated.
But it works now?? Maybe you fixed something by chance in the kernel which also fixed uboot?
Or maybe it does not always trigger? I tried a few times now and it always worked though, it never worked 5 days ago...

If you want to to check it out or lend my drive, I am in Tokyo until Sunday!

**Comment by phansel** [comment]
> A whole pile of u-boot USB fixes went in recently

> 3 linux-edge and mesa-edge packages were updated. But it works now?? Maybe you fixed something by chance in the kernel which also fixed uboot?

sounds like this issue can be closed?

**Comment by jannau** [comment]
closing as probably resolved through u-boot usb fixes
