### ISSUE TITLE
AsahiLinux Performance / Benchmark comparsions

### ISSUE THREAD

**Issue by hackgrid** [AsahiLinux/linux#155]
Hi,

I hope its okay, to share and collect some performance comparsions here?

MacBook Air M1 (2020), 8GB (maximum performance profile)

BrowserBench Speedometer 2.1 (https://browserbench.org/Speedometer2.1/)
- MacOSX 13.4 Google Chrome 114: 330 Points
- AsahiLinux (-edge updated as of 2023.06.10) Chromium 114: 293 points

Only a difference of 10%, thats pretty awesome! :)

GLXGears
- 69112 points

Just to document that current state, can you run GLXGears somehow on MacOSX?

**Comment by marcan** [comment]
The issue tracker is not the place for this.
