### ISSUE TITLE
M1 mini ethernet module missing firmware info

### ISSUE THREAD

**Issue by tobhe** [AsahiLinux/linux#162]
I found that the tg3 driver used in the m1 mini doesn't correctly declare all its firmware files. This leads to files not being included in the initrd which causes the interface bringup to fail.

This was fixed in:
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=046f753da6143ee16452966915087ec8b0de3c70

**Comment by jannau** [comment]
fix is included via upstream since asahi-6.5-1
