### ISSUE TITLE
GPU hang in normal use

### ISSUE THREAD

**Issue by rosefromthedead** [AsahiLinux/linux#163]
I had firefox and foot open in sway, with a jitsi call in an inactive tab, and the whole display froze while loading a gitlab page.
[asahi-diagnose-20230713-114944.txt](https://github.com/AsahiLinux/linux/files/12053174/asahi-diagnose-20230713-114944.txt)

**Comment by jannau** [comment]
The whole display including the mouse pointer? This looks like it might be the issue described as firefox hang in #72
If that is the case it is hopefully fixed in asahi-6.3-13.

**Comment by rosefromthedead** [comment]
Yeah, including the mouse pointer. Happy for this to be closed if people think it's fixed since I'm not going to be able to reproduce it ever again :)

**Comment by jannau** [comment]
It's not the GPU driver. I missed `drm_atomic_helper_wait_for_fences` in the call trace. That kms/atomic and thus the display driverwould be the display. That's a better match for the full display freeze anyway.

This is not necessarily a bug the in the dispaly driver, it waits on the fence of the new framebuffer. Either it waits for some reason on the wrong fence or the fence is never signaled.

Sway could have run into same issue as firefox resulting in a framebuffer never signaled as completed and thus hanging the atomic swap indefinitely. Hard to debug this further considering this was never reported before and we do not even know where to look for the bug.

**Comment by marcan** [comment]
This is probably that bug that was fixed in -13, yes. Let's close this and we can reopen if it keeps happening.
