### ISSUE TITLE
Charge Limit in Advanced Power Settings doesn't get saved

### ISSUE THREAD

**Issue by juvrajsb** [AsahiLinux/linux#168]
I noticed that if I set a charge limit, after I restart it goes to the default 100%.

OS: Arch Linux ARM aarch64 
Host: Apple MacBook Air (M1, 2020)
Kernel: 6.3.0-asahi-13-1-edge-ARCH

**Comment by sebastianwagner** [comment]
It would be up to the distribution to properly set those values upon boot.
If you like you can use a [workaround(gist)](https://gist.github.com/sebastianwagner/6425949604824cfa800918e163c0b6ef) involving systemd unit files.

**Comment by jannau** [comment]
there's an udev rule from https://social.treehouse.systems/@AsahiLinux/110560192550506827 short enough to quote here:
```
echo 'SUBSYSTEM=="power_supply", KERNEL=="macsmc-battery", ATTR{charge_control_end_threshold}="80"' | sudo tee /etc/udev/rules.d/10-battery.rules
```
