### ISSUE TITLE
Keyboard backlight not fully turned off on lowest brightness setting

### ISSUE THREAD

**Issue by putuprema** [AsahiLinux/linux#169]
Not sure if this is the correct place to report this, but I noticed when I set the keyboard backlight brightness in KDE to the lowest setting, the backlight does not really turned off. See the image I took below on the F6 key.

Booting macOS:
![20230726_040050](https://github.com/AsahiLinux/linux/assets/34528090/d2bc8b59-63b2-4aac-923f-f9530adf59ca)

Booting Arch Linux ARM (you can see there's a little bit of light still):
![20230726_035112](https://github.com/AsahiLinux/linux/assets/34528090/35678f98-1c2c-4614-b802-ad6da6db456b)

Output of asahi-diagnose:
[asahi-diagnose-20230726-035147.txt](https://github.com/AsahiLinux/linux/files/12208394/asahi-diagnose-20230726-035147.txt)

Let me know if more diagnostic files is needed.

**Comment by marcan** [comment]
Heh, I had to go into a pitch dark room to notice.

This probably doesn't affect power consumption in a measurable way at that PWM level, but we should get it fixed.

**Comment by WhatAmISupposedToPutHere** [comment]
This is a kde bug, even if the slider is in the lowest position, the requested brightness is still above 0. Manually writing 0 to the relevant sysfs file will turn the backlight off entirely.

**Comment by rxhfcy** [comment]
> Manually writing 0 to the relevant sysfs file will turn the backlight off entirely

btw this appears to be the way to write the aforementioned 0 to turn off the keyboard backlight:

```shell
echo 0 | sudo tee /sys/class/leds/kbd_backlight/brightness
```

**Comment by jannau** [comment]
fixed in https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/3166 but as farr as I can see only for Plasma 6 so far.

**Comment by marcan** [comment]
Nothing left to do here then.
