### ISSUE TITLE
Broken audio on latest kernel.

### ISSUE THREAD

**Issue by nolight132** [AsahiLinux/linux#171]
OS: Arch Linux ARM aarch64
Host: Apple MacBook Air (M1, 2020)
Kernel: 6.3.0-asahi-13-1-edge-ARCH

It worked before `pacman -Syu` on my AirPods Pro. 

Here are the logs during boot mentioning audio:
`Aug 04 00:19:44 archbook kernel:  Secondary: opening PCM device 'Secondary' with no audio route configured (bad settings applied to the sound card)
Aug 04 00:19:44 archbook kernel:  Secondary: ASoC: error at snd_soc_link_hw_params on Secondary: -22`

I hope it helps, but if not than I'm ready to provide more logs, just not sure which are required.

**Comment by jannau** [comment]
Those messages have nothing to do with audio over bluetooth. Please describe the error in more detail. Does pairing/connecting the AirPods Pro work? Do you hear noise while playing audio? Do you use a 2.4GHz wlan? Does the noise go away if you disable the wlan?

**Comment by nolight132** [comment]
> Those messages have nothing to do with audio over bluetooth. Please describe the error in more detail. Does pairing/connecting the AirPods Pro work? Do you hear noise while playing audio? Do you use a 2.4GHz wlan? Does the noise go away if you disable the wlan?

Now that I look at it, it's actually fine with audio-only files, the problem only occurs with video in LibreWolf, the playback just won't start. However, video files in telegram-desktop (.mov) do play but for some reason only through external players, not in the Telegram itself. 

```
Aug 04 12:43:19 archbook mpp[1814]: vcodec_service: open vcodec_service (null) failed
Aug 04 12:43:19 archbook mpp[1814]: hal_h264d_api: mpp_dev_init failed ret: -1
```
This message is constantly being displayed.

Edit: After realizing the that the problem roots from codecs, I replaced `ffmpeg-mmp` with `ffmpeg` and therefore resolved the issue.
