### ISSUE TITLE
missing TILDE_QUIRK fix for new mac keyboards

### ISSUE THREAD

**Issue by Fl1tzi** [AsahiLinux/linux#21]
While working on [this issue](https://github.com/AsahiLinux/xkeyboard-config/issues/2), @mixi found out that the switched °^ and <> could be because of the driver not setting it right.

[This commit](https://github.com/AsahiLinux/linux/commit/e26a78057c25dd56f112d536319c38735ed92ba4) was the last update I found on this issue. But there doesn't seem to be a rule for the new Macbooks. The [commit](https://github.com/AsahiLinux/linux/commit/dede6485bd8d3c08a4552560491add3caa540b32) for the new device id's was created just 12 days ago, so it's probably not added yet.

That would mean that these macs would have this bug:

- APPLE_MACBOOK_AIR_2020
- APPLE_MACBOOK_PRO13_2020
- APPLE_MACBOOK_PRO14_2021
 - APPLE_MACBOOK_PRO16_2021

**Comment by alxdrl** [comment]
works for me with latest kernel on MBA 2020 w/ french keyboard (fix maybe was https://github.com/AsahiLinux/linux/commit/490988c11c470e9745d7db5cd00c812dc8e07cbc)
