### ISSUE TITLE
Cursor leaving a "burn mark" on GNOME after three finger vertical swipe 

### ISSUE THREAD

**Issue by Kidplayer666** [AsahiLinux/linux#212]
When using video capture, the issue was not visible on the captured video, therefore the bad phone recording.
https://github.com/AsahiLinux/linux/assets/67331281/0d9d3c52-7459-446e-ac19-a3219f53de67

**Comment by jonas2515** [comment]
This is a bug in mutter: Asahi uses software cursors currently, and mutter fails to invalidate the whole cursor region on some repaints. Feel free to open a bug with mutter if you want, mutter developers are aware of this issue already though.

**Comment by heywoodlh** [comment]
I seem to be encountering this, running GNOME + Wayland. I suspect this is related, as I notice my frame rate drops when cursor artifacts show up around Firefox for me: https://gitlab.gnome.org/GNOME/mutter/-/issues/3247

Tried the setting following environment variables without success:

```
COGL_DEBUG=sync-frame
CLUTTER_PAINT=disable-dynamic-max-render-time
```

Is there any potential workaround to get GNOME+Mutter to consistently deliver 60 FPS?

**Comment by marcan** [comment]
Please file this with Mutter.
