### ISSUE TITLE
HDMI output doesn't seem to work, Macbook Pro M1

### ISSUE THREAD

**Issue by atodorov** [AsahiLinux/linux#219]
I tried the built-in HDMI output and a USB C to HDMI converter I've used in the past. None worked. Not sure what other info I should provide.

Is this a known issue perhaps ?

**Comment by mersinvald** [comment]
HDMI is routed via thunderbolt on M1 macbooks, and thunderbolt is not supported in Asahi yet. Same goes for the adapters. 

The current workaround is to use DisplayLink adapter which works via USB and a has a user space service.

Here's the wiki page with the feature support table: https://github.com/AsahiLinux/docs/wiki/Feature-Support

**Comment by TerrorSquad** [comment]
Hi @mersinvald 

Can you please suggest some adapters that do work?

**Comment by atodorov** [comment]
> The current workaround is to use DisplayLink adapter which works via USB and a has a user space service.

I'm back on this issue.  Which is the user space service? I have several USB-HDMI adapters which have worked in the past for me with Linux on Mac, however none worked this time. I'm suspecting I don't have this service installed or it isn't running.

**Comment by christianhorn** [comment]
I think the idea for the workaround is to have something connected via USB which speaks a protocol like DisplayLink (might be a monitor, or an adapter which outputs HDMI) and have on Linux a userland component running which speaks DisplayLink. I actually wonder if also a Raspi or such could do that.. but then rather not with DisplayLink but something else.

**Comment by christianhorn** [comment]
FWIW, I was curious if I can get the latency down with a screen renedered on a MacBook runnin Asahi, a system connected via GBit ethernet, and a monitor connected via HDMI to that system. Looks like 0.2sec to me. 

Details: https://fluxcoil.net/wiki/software/wayland_screenbeam

**Comment by ydalton** [comment]
It looks like experiment HDMI out support has been enabled in 14 and 16 inch MacBook Pro models in the latest kernel. Update and see if it works.

**Comment by sequencer** [comment]
Is DPALT(Type-C Display) supported?

**Comment by szbergeron** [comment]
@sequencer type-C out is not supported in the current kernel, only HDMI out on the M1 machines that have a hardware HDMI port

**Comment by christianhorn** [comment]
No USB-C indeed as of now, but HDMI out works also on for example Macbook pro M2. I use it since yesterday, and https://github.com/AsahiLinux/docs/wiki/M2-Series-Feature-Support is also listing it.

**Comment by jannau** [comment]
Physical HDMI ports like oon the 14/16 inch Macbook Pros are now supported. DisplayPort Alt-Mode or DisplayPort over Thunderbolt/USB4 via the USB-C ports is not supported. No need to keep issues open for missing HW support
