### ISSUE TITLE
actual_brightness reported by DCP subsystem is wrong

### ISSUE THREAD

**Issue by rowanG077** [AsahiLinux/linux#223]
Platform: M2 Max

I noticed that `actual_brightness` is constant even though I can change the brightness with no issues.

```
[root@rowanG-nixos:/home/rowan.goemans]# cat /sys/class/backlight/apple-panel-bl/brightness 
100

[root@rowanG-nixos:/home/rowan.goemans]# cat /sys/class/backlight/apple-panel-bl/actual_brightness 
300

[root@rowanG-nixos:/home/rowan.goemans]# echo 500 > /sys/class/backlight/apple-panel-bl/brightness 

[root@rowanG-nixos:/home/rowan.goemans]# cat /sys/class/backlight/apple-panel-bl/brightness 
500

[root@rowanG-nixos:/home/rowan.goemans]# cat /sys/class/backlight/apple-panel-bl/actual_brightness 
300
```

**Comment by jgouly** [comment]
This is what causes `systemd-backlight@.service` to restore the wrong screen brightness at boot.

**Comment by jgouly** [comment]
Looks like this will be fixed by https://github.com/AsahiLinux/linux/commit/b07f7c0f9f78aeaa9c318da573a4f40edf3d1ddb (thanks @jannau!), I haven't tried it yet.

**Comment by rowanG077** [comment]
I can confirm that this is fixed now. Thank you @jannau
