### ISSUE TITLE
Keyboard BackLight Lagging (Asahi Fedora Remix)

### ISSUE THREAD

**Issue by mazdakdev** [AsahiLinux/linux#253]
The OS lags a bit when one changes the keyboard backlight value through GNOME.

Device: MacBook Pro 2020 m1

By the way, It's fabolous. I mean it's way better than the Asahi alarm alpha version.
Really appreciate your work.

**Comment by flightmansam** [comment]
This seems to be fixed now. Id recommend closing the issue.
