### ISSUE TITLE
When will there be support for microphones

### ISSUE THREAD

**Issue by Heinrich-XIAO** [AsahiLinux/linux#267]

**Comment by UserC2** [comment]
Refer to the [Asahi Linux Wiki](https://github.com/AsahiLinux/docs/wiki):
* It's being worked on for [all M1 devices](https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#m1-devices) and [M2 devices](https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#m1-devices)
* There is nobody working on microphone support for [M2 Pro/Max/Ultra devices](https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#m1-devices) or [any M3 devices](https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#m1-devices)

**Comment by marcan** [comment]
When it's ready. Please don't open issues for missing features, we know.
