### ISSUE TITLE
fedora Asahi remix 39 boot into black screen while the external hdmi monitor work. 

### ISSUE THREAD

**Issue by uzrgithub** [AsahiLinux/linux#273]
I am using Macbook Pro M1 Pro running Mac OS 14.3 and I face issue when booting fedora asahi remix 39, the built in display turns black while the external monitor works, I have tried to solve this issue using nomodeset, and nomodeset solved this issue partially by making the built in display work and externel hdmi monitor continue to work as normal, but nomodeset disables the apple m1 pro gpu, and the system uses software rendering instead of the gpu.

On other hand while I was searching for a solution, I found the rescue mode, I tried it and got this message
`apple-dcp 289c00000.dcp: Failed to get dp-xbar: -517`

![57e140a77dbd6e31d2953b86e6205d0da48d3960_2_1332x1000](https://github.com/AsahiLinux/linux/assets/161166692/f7ec6586-ae59-418c-b9a4-af68a6d81372)

This happens when the system booted without adding nomodeset to grub.

The good news is the external monitor which is plugged in using hdmi was working, as well the Apple M1 Pro (G135 CO) gpu, except the built in display it was black, all of this happened when the system booted without nomodeset added to grub.

the summary of the issue:

when nomodeset added to grub:

* built in display and externel monitor is going to work.
* apple m1 pro gpu is going to be disabled and the system is going to use software rendering instead.

when the system boot without nomodeset added to grub:

* apple m1 pro gpu and the external will work fine.
* the built in display is going to be black.

I hope there is a solution for this issue.

here is the boot log file:
[output.txt](https://github.com/AsahiLinux/linux/files/14394642/output.txt)

**Comment by uzrgithub** [comment]
I have solved this issue by downgrading to Mac OS 13.6 using DFU mode, I am not an expert to say the real cause of this problem but I believe there is a firmware issue in Mac OS Sonoma that cause the screen to be black.

**Comment by jannau** [comment]
The reason why the internal display failed is `Feb 21 17:55:24 fedora kernel: apple-dcp 38bc00000.dcp: received unknown callback D454` (`"IOMFBStatus IOMFB::MemDescRelay::prepare(unsigned int, unsigned int)"`). It's unclear why that would be send. It has to be something the 14.3 iboot does during DCP init but I haven't seen this with 14.2 / 14.4

**Comment by jannau** [comment]
This will be fixed on the next kernel update

**Comment by uzrgithub** [comment]
> This will be fixed on the next kernel update
First and foremost, I want to express my gratitude for your dedicated efforts in enhancing the stability of Asahi Linux. I'm curious to know when the next kernel update is scheduled for release?.

**Comment by jannau** [comment]
The fix is included in `6.8.9-402.asahi`. I ran into this myself after changing the display refresh rate to 50Hz (using macOS 14.4 system firmware)
