### ISSUE TITLE
?

### ISSUE THREAD

**Issue by n-bc** [AsahiLinux/linux#28]
Last login: Wed Apr 27 17:36:44 on ttys000
caiyanzhe@caiyanzhedeMacBook-Air ~ % cn.akinator.com
zsh: command not found: cn.akinator.com
caiyanzhe@caiyanzhedeMacBook-Air ~ % curl https://alx.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1440  100  1440    0     0    794      0  0:00:01  0:00:01 --:--:--   798

Bootstrapping installer:
  Checking version...
  Version: v0.3.28
  Downloading...
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 13 ms: Connection refused
    Error downloading installer_data.json. GitHub might be blocked in your network.
    Please consider using a VPN if you experience issues.
    Trying workaround...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.

By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): N

Collecting system information...
  Product name: MacBook Air (M1, 2020)
  SoC: Apple M1
  Device class: j313ap
  Product type: MacBookAir10,1
  Board ID: 0x26
  Chip ID: 0x8103
  System firmware: iBoot-7459.101.2
  Boot UUID: 1304A755-C43A-439A-A613-8167134907AE
  Boot VGID: 1304A755-C43A-439A-A613-8167134907AE
  Default boot VGID: 1304A755-C43A-439A-A613-8167134907AE
  Boot mode: macOS
  OS version: 12.3 (21E230)
  System rOS version: 12.3 (21E230)
  No Fallback rOS
  Login user: caiyanzhe

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.4 [disk3s1, 1304A755-C43A-439A-A613-8167134907AE]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.3 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r

We're going to resize this partition:
  APFS [Macintosh HD] (245.11 GB, 6 volumes)
  Total size: 245.11 GB
  Free space: 154.88 GB
  Minimum free space: 38.00 GB
  Minimum total size: 128.23 GB (52.32%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (min): 180GB

Resizing will free up 65.11 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 65,107,591,168 bytes and targeting a new physical store size of 179,999,604,736 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 93,281,320,960 bytes
Resizing APFS Container designated by APFS Container Reference disk3
The specific APFS Physical Store being resized is disk0s2
Verifying storage system
Using live mode
Performing fsck_apfs -n -x -l /dev/disk0s2
Checking the container superblock
Checking the space manager
Checking the space manager free queue trees
Checking the object map
Checking the encryption key structures
Checking volume /dev/rdisk3s1
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking snapshot 1 of 2 (com.apple.os.update-2289385E1A6FCCF05D444673FB1FEB06DDCF82A4C723EAD53AF1F3E08872CE0F)
Checking snapshot 2 of 2 (com.apple.os.update-MSUPrepareUpdate)
Checking the fsroot tree
Checking the file extent tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s1 appears to be OK
Checking volume /dev/rdisk3s2
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s2 appears to be OK
Checking volume /dev/rdisk3s3
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s3 appears to be OK
Checking volume /dev/rdisk3s4
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s4 appears to be OK
Checking volume /dev/rdisk3s5
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the document ID tree
Checking the fsroot tree
error: doc-id tree: record exists for doc-id 39748, file-id 27209630 but no inode references this doc-id
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s5 was found to be corrupt and needs to be repaired
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 appears to be OK
Verifying allocated space
Performing deferred repairs
error: doc-id tree record exists for doc-id 39748, but no inode references this doc-id
Deferred repairs skipped
The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 179999604736
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '179999604736']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
caiyanzhe@caiyanzhedeMacBook-Air ~ %

**Comment by DavidBuchanan314** [comment]
https://github.com/AsahiLinux/asahi-installer/issues/81

**Comment by retromuz** [comment]
Existing OSX partition `/dev/rdisk3s5 ` has errors. The installer skipped the repair since it is "differed". I'm not sure what this actually means. Someone else can shed some light on this?

**Comment by DavidBuchanan314** [comment]
The issue I linked above contains all light-shedding necessary.

**Comment by n-bc** [comment]
Thank you very much!
