### ISSUE TITLE
Enable palm rejection by default?

### ISSUE THREAD

**Issue by rxhfcy** [AsahiLinux/linux#280]
Is it possible for the Asahi project to "flip the switch" to enable palm rejection by default (or is this something every distribution must configure separately)?

I keep getting phantom cursor movements when typing on my laptop keyboard (by accidentally touching the trackpad with the base of my thumbs). I don't use tap to click. This doesn't happen on macOS at all.

[This Reddit comment thread](https://www.reddit.com/r/AsahiLinux/comments/1ahmous/comment/koqnwee/) started by @marcan seems relevant.

**Comment by Ahwxorg** [comment]
+1, also have this issue. Even with the following in my Hyprland config:

```ini
input {
    kb_layout = us
    follow_mouse = 1 # focus window under mouse cursor
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    # accel_profile = flat # for when I want a quick and dirty fix, for i.e. gaming mice.
    # force_no_accel = true # ^^
    touchpad {
        natural_scroll = no
        clickfinger_behavior = true # helps a tiny bit
        tap-to-click = false # helps a tiny bit
        disable_while_typing = true # helps a tiny bit
    }
}
```

I am on Gentoo, latest kernel for Gentoo Asahi (which is `6.6.0-asahi-15` atm)

**Comment by marcan** [comment]
See here: https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/897
