### ISSUE TITLE
Asahi as Docker Virtual Machine?

### ISSUE THREAD

**Issue by matssk** [AsahiLinux/linux#285]
On MacOS it is currently not possible to use GPU accelerated Docker containers, so any LLM code has to be running directly on the Mac.

Will the GPU driver of Asahi enable Apple GPU support in Docker containers? Essentially Docker does not support GPUs on Mac because containers is a Linux feature, so it has to run a Linux VM, and the Linux kernel on that VM does not have drivers Apple GPUs to support Metal Performance Shaders.

It would be great to be able to run PyTorch, HuggingFace transformers etc in Docker containers on Mac.

**Comment by alyssarosenzweig** [comment]
> Will the GPU driver of Asahi enable Apple GPU support in Docker containers? 

No, feel free to run native asahi though
