### ISSUE TITLE
M3 (max) GPU and other support?

### ISSUE THREAD

**Issue by gigatexal** [AsahiLinux/linux#286]
Hi. I think I created this in the wrong place. At first I added this to the docs. https://github.com/AsahiLinux/docs/issues/111#issue-2242342489

The question is clarifying the M3 support. M2 and M1 have their GPU supported and have installers etc. Is M3 stuff coming? If so could I help in some way? Monetarily or by testing? A number of things in the matrix were TBA and was curious if more of a timeline was available. 

I just bought a 14 inch M3 max and was looking forward to running Asahi on it.

thank you all for the amazing feats of late either way

**Comment by gigatexal** [comment]
Answered here: https://social.treehouse.systems/@marcan/112277289414246878

**Comment by liangqi** [comment]
> Answered here: https://social.treehouse.systems/@marcan/112277289414246878

The page you were looking for doesn't exist here anymore.
