### ISSUE TITLE
Issue building audio drivers with 6.8.6-3

### ISSUE THREAD

**Issue by faddat** [AsahiLinux/linux#289]
Here's what I've got:

```log
  MODPOST Module.symvers
ERROR: modpost: "dcp_audio_register" [drivers/gpu/drm/apple/apple_dcp.ko] undefined!
ERROR: modpost: "dcp_audio_unregister" [drivers/gpu/drm/apple/apple_dcp.ko] undefined!
make[3]: *** [/home/alarm/pkgbuilds/linux-asahi/src/linux-asahi-6.8.6-3/scripts/Makefile.modpost:145: Module.symvers] Error 1
make[2]: *** [/home/alarm/pkgbuilds/linux-asahi/src/linux-asahi-6.8.6-3/Makefile:1872: modpost] Error 2
make[1]: *** [/home/alarm/pkgbuilds/linux-asahi/src/linux-asahi-6.8.6-3/Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/home/alarm/pkgbuilds/linux-asahi/src/linux-asahi-6.8.6-3/build/edge'
make: *** [Makefile:240: __sub-make] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I'm using Arch, and trying to update the PKGBUILD because welp, yeah I'm gonna be that holdout guy who uses asahi on arch.

Thoughts?

**Comment by faddat** [comment]
Oh, I see:

https://github.com/AsahiLinux/linux/commit/587d84ac56796a0cdbbb7d28b089fe6f988736f7

:)

Please close this if that is the fix I think it is.

**Comment by jannau** [comment]
no, that doesn't fix the build error. Build is just  broken without `CONFIG_DRM_APPLE_AUDIO=y`. I'll push a fix but not sure if we will immediately tag that.

**Comment by jannau** [comment]
fixed in https://github.com/jannau/linux/commit/0f3bd58d7dce8942b3b685c6f1510dfe1838c029

https://github.com/jannau/linux/commit/4adfa77aacb0bf0ececb14c7db7a0f436bc85e48 contains warning fixes when building without `CONFIG_DRM_APPLE_AUDIO=y`

**Comment by faddat** [comment]
oh, I see, and thanks so much!

I'll add that to the config :).

**Comment by faddat** [comment]
linux-asahi-ed
