### ISSUE TITLE
GLib throwing error during ´malloc´ operation

### ISSUE THREAD

**Issue by Seba-T** [AsahiLinux/linux#29]
I encountered this bug after downloading and trying to run telegram; the same outcome occurred by using both snap and pacman. I tried to run the executable from the terminal, and I got the following message: 
```
<jemalloc>: Unsupported system page size
GLib (gthread-posix.c): Unexpected error from C library during 'malloc': Cannot allocate memory.  Aborting.
[1]    2988 IOT instruction (core dumped)  ./telegram-desktop
```

**Comment by rowanG077** [comment]
jemalloc doesn't support 16k pages yet. See here for all software that is know to have issues: https://github.com/AsahiLinux/docs/wiki/Software-known-to-have-issues-with-16k-page-size

**Comment by Seba-T** [comment]
Thanks, I just came across that issue myself, I'll close this one to avoid redundancy
