### ISSUE TITLE
DisplayLink issues

### ISSUE THREAD

**Issue by Ahwxorg** [AsahiLinux/linux#291]
Thank you all for you continued work on Asahi Linux! Since I use my laptop as a desktop replacement, I use 3 external displays with it. For this purpose, I used to use a Thunderbolt dock (and max. 2 external displays, since Apple...), but that is not supported on Asahi yet, so now I use a DisplayLink dock. I don't know if this is the correct place to report this, but DisplayLink seems to work fine with Windows and macOS. I compiled the evdi driver and installed that, that works fine, since it works on Xorg with all displays. Sadly, Xorg is really laggy and old and that makes it barely usable. With Wayland, only one external monitor from the dock is connected. Please take a look at https://github.com/Ahwxorg/computers/issues/6.

**Comment by Ahwxorg** [comment]
[asahi-diagnose-20240503-082727.txt](https://github.com/AsahiLinux/linux/files/15196770/asahi-diagnose-20240503-082727.txt)

**Comment by Ahwxorg** [comment]
I've rebooted many times, and am on the Asahi dist kernel on Gentoo.

**Comment by marcan** [comment]
DisplayLink is a proprietary technology with no fully open source drivers, so we can't offer support for it. We also do not support Xorg sessions. Sorry.
