### ISSUE TITLE
bluetooth pairing not working on Asahilinux Fedora 40 kernels higher than 6.8.8-400

### ISSUE THREAD

**Issue by gojun077** [AsahiLinux/linux#293]
I did an upgrade from Asahilinux Fedora 39 to Fedora 40 yesterday and experienced bluetooth pairing failures with my BT mouse and keyboard. See Fedoraforum thread [116614](https://discussion.fedoraproject.org/t/unable-to-pair-bluetooth-keyboard-after-system-upgrade-to-40/116614)

When pairing, the error `Failed to pair: org.bluez.Error.AuthenticationFailed` appears in `bluetoothctl` for trusted devices working just fine in Fedora 39.

The upgrade installs kernel `6.8.9-402` btw. After installing older f40 kernel 6.8.8-400 and rebooting into the older kernel, bluetooth pairing works again. I'm not sure if this is an Asahilinux issue or a wider Fedora 40 issue; if it is the latter, I can open a bug in Redhat Bugzilla.

Thanks,
Peter

**Comment by jannau** [comment]
this is fixed in https://github.com/AsahiLinux/linux/releases/tag/asahi-6.8.9-5 but a updated Fedora kernel with the fix is still missing

**Comment by jannau** [comment]
Updated Fedora kernel `kernel-16k-6.8.9-403.asahi` with the fix is now available.
