### ISSUE TITLE
ODirect not working

### ISSUE THREAD

**Issue by mronstro** [AsahiLinux/linux#30]
I installed Asahi Linux on an Apple M1 Pro laptop and it worked like a charm.
I installed the latest branch of RonDB. This branch is 22.05.
I managed to compile after installing a few extra packages.
I executed a number of test cases using MTR (MysqlTestRun).
Most test cases failed in a method called set_direct_io which sets up the file to
use O_DIRECT using fcntl calls. These calls fail. So I presume that O_DIRECT is
not yet supported by the NVMe driver.

**Comment by axboe** [comment]
The application is buggy and assumes 4k pages, and asahi runs 16k pages by default. O_DIRECT isn't a property of the storage driver, it's just as read/write as far as that is concerned.

**Comment by mronstro** [comment]
Presume by application that you mean RonDB, RonDB actually always writes in 32 kB chunks, so a 16k page size shouldn't
be an issue I presume. However the bug happens in that fcntl(fileDescriptor, , SETFL, flags | O_DIRECT) fails where flags
is retrieved with a fcntl call using GETFL. This call is done after opening the file.

**Comment by mronstro** [comment]
Actually looking at the function set_direct_io you might be right, will look another round to see what goes on
in the RonDB code.

**Comment by mronstro** [comment]
Yep, you were right. Seems like it depends on 4k page size. Interesting.

**Comment by mronstro** [comment]
Debugged the code a bit more, it seems that fstat returns that block_size is 4k, but when one attempts to use this
size in a pread call, the pread returns EINVAL indicating that O_DIRECT cannot be used with 4k alignment only.
However should not the fstat return 16k if that is the minimum alignment for O_DIRECT?

**Comment by axboe** [comment]
No, stat correctly returns the file system block size, which is not the same thing as required memory alignment. They just happen to overlap on eg x86, because the page size is 4K as well. You can query the latter with sysconf(_SC_PAGESIZE);

**Comment by mronstro** [comment]
Thx, read up a bit on O_DIRECT, seem to be common consensus that it is a bit hard to figure out the alignment size.
But obviously the current code in RonDB needs to be extended to handle the requirements in Asahi Linux.

**Comment by mronstro** [comment]
Thx for the assistance, will close this issue since it is an issue in RonDB rather.
