### ISSUE TITLE
This project is bias to the rich elites who can afford overpriced and throwaway at this point apple products

### ISSUE THREAD

**Issue by codenameneptune** [AsahiLinux/linux#300]
By wasting time on something only people with sufficient money can ever afford to use or work on you create an automatic elitist project. Coupled with significant issues regarding Apple Silicon hardware in terms of user impact you declare how you only care for the rich and well off and OF THOSE JUST the ones willing to obey your rules without question or face instant extermination.

**Comment by DavidBuchanan314** [comment]
Not contributing to asahi is free

**Comment by leifliddy** [comment]
The definition of elite is ```a select group that is superior in terms of ability or qualities to the rest of a group or society``` 
lol....that pretty sums up all Linux users. Not sure what being rich has to do with anything. 
At this moment you can but a mac mini m2 on amazon.com for $479.00 -- pretty sure you don't have to be rich to buy that.

**Comment by GuillaumeDIDIER** [comment]
And I assume second hand M1 Mac minis can thus be found for even less than that.
