### ISSUE TITLE
Linux paging support

### ISSUE THREAD

**Issue by predator-111** [AsahiLinux/linux#306]
Hi, I am new to Linux. Can anyone please suggest a way to run updated version of Linux with 3 level of paging with RISC-V architecture. By default it supports 5 level of paging. I want to compile this for a specific hardware which supports 3 level of page table only.

**Comment by jannau** [comment]
This is a very risc-v specific question. It's verly unlikely someone here can answer this. This project / repository is specifically for supporting Apple Silicon SoCs (ARMv8/9 based) in linux.

The best alternative I can think of is the [linux-riscv mailing list](http://lists.infradead.org/mailman/listinfo/linux-riscv) but there might be better alternatives for the platform you're looking at.
