### ISSUE TITLE
Cannot seem to assign static IP

### ISSUE THREAD

**Issue by adamtheadmin** [AsahiLinux/linux#31]
Just reporting, but it seems that the system doesn't want to let me use a static IP instead of the DHCP assigned IP.

I tried to follow a few different tutorials using both eth0 and enp3s0 interfaces with no luck.

**Comment by marcan** [comment]
This isn't a kernel issue. Please seek help in general Linux support channels, as this can't have anything to do with Asahi / be specific to Macs.
