### ISSUE TITLE
Kernel crash on boot with 6.9.9 (intermittent) - SError Interrupt on CPU0

### ISSUE THREAD

**Issue by binaryfields** [AsahiLinux/linux#310]
I am running Fedora 40 with the latest kernel 6.9.9-403 on MacBook Pro M2 Max. Upon booting into the system, the kernel panics before booting into the desktop environment. The issue started to happen with upgrade to the latest kernel, previous kernel 6.6.3-414 worked without any problems.

The issue is intermittent, so it only happens once in a while and it usually goes away with a reboot. It happens once every few reboots (usually between 2-10). I cannot get logs from journald so I'm attaching a screenshot of the boot screen (apologies for quality).

![kernel699-serror](https://github.com/user-attachments/assets/b847039a-f7d3-4790-808f-bb9c6c1410c6)

**Comment by jannau** [comment]
That is the controller for the SD card reader. If you aren't using it add `module_blacklist=sdhci_pci` to the boot args.

**Comment by binaryfields** [comment]
Thank you, I'll give that a shot and keep you posted.

**Comment by zzywysm** [comment]
Rather than blacklisting the driver, maybe try turning off autosuspend on that driver instead?

https://github.com/tpwrules/nixos-apple-silicon/blob/b0a2376f6c164a0af963d47386c064cc6fdcd5ea/apple-silicon-support/modules/kernel/default.nix#L85

**Comment by jannau** [comment]
Change for Fedora-Asahi-Remix: https://pagure.io/fedora-asahi/fedora-asahi-remix-scripts/pull-request/7

**Comment by marcan** [comment]
This is worked around.

**Comment by mkurz** [comment]
- Fix will be moved to asahi-scripts: https://github.com/AsahiLinux/asahi-scripts/pull/56
