### ISSUE TITLE
Where can I download asahi linux?

### ISSUE THREAD

**Issue by ghostforest** [AsahiLinux/linux#320]
I only find links that install asahi linux. I cant seem to find anything to download a .iso?

**Comment by GuillaumeDIDIER** [comment]
It is not really possible to download an ISO because of :
1. The way Apple Silicon system boot
2. Apple restricts redistribution of some of the requisite pieces, which have to be downloaded straight from them

**Comment by ghostforest** [comment]
How can I test Asahi with a virtual machine then? I guess I cant?

**Comment by GuillaumeDIDIER** [comment]
Asahi is not meant to be in a virtual machine. It only deals with the bare-metal support for Apple Silicon, and is very thin layer added to a ARM Fedora KDE, dealing with HW stuff.

To test, you can install an ARM Fedora KDE on your favourite VM software (ideally with some guest GPU acceleration).

**Comment by ghostforest** [comment]
Thank you for your time, thank you for the infos.
