### ISSUE TITLE
add support for hardware-accelerated mesh shaders on >M3

### ISSUE THREAD

**Issue by csutora** [AsahiLinux/linux#325]
hi!

Apple Silicon supports mesh shaders in hardware since M3, so it would be nice if the OpenGL driver could use the hardware capabilities on the M3 variants instead of running them as compute shaders.

newer NVIDIA cards already have support for this in their drivers, and it seems like AMD will soon add support to their drivers too. is this on the roadmap for Asahi Linux?

please consider it.
have a good one!

**Comment by GuillaumeDIDIER** [comment]
From what I've gathered, we only have a single awesome Alyssa R. doing the GPU stuff in mesa, and she has stated she was not going to bring up M3 until she's finished dealing with M1 and M2 fully (which include Vulcan and serious polish).

I guess she might give you a few pointers if you delved into bringing up M3 though ^^'

**Comment by csutora** [comment]
thanks for the response, i understand why she'd prefer to finish those first. good to know.

regarding doing it myself, i'm in the process of learning about the topic, so i guess we'll just have to see who gets there first, her or i. i'll leave the issue open just in case someone wants to work on/talk about this in the meantime.

**Comment by jannau** [comment]
please do not use issue as feature requests

**Comment by csutora** [comment]
i'm sorry for using the wrong channel for this. could you be more specific, where should one go to request features?
