### ISSUE TITLE
Auto boot after power loss on M1 Mini

### ISSUE THREAD

**Issue by jmif** [AsahiLinux/linux#334]
I'm trying to get my M1 Mini running Asahi Linux to boot after a power loss, is this possible to do?  I've tried to boot into macOS and enable it there (System Preference -> Energy Saver -> Start up automatically after a power failure) but when I simulate a power loss by unplugging it / replugging it it doesn't automatically boot.

Thanks!

**Comment by marcan** [comment]
The setting (also available at `/sys/bus/platform/devices/macsmc-reboot/ac_power_mode`) only allows auto power off on *power loss* (with the machine powered on), equivalent to the "restore last state" setting on PC BIOSes. There is not "always power on" option, we can't implement support for things the hardware can't do.

If the macOS setting does not work at all (nor does the Linux one), not even when pulling the plug while powered up, then that's a hardware/firmware bug and you should file it with Apple, there's nothing we can do. The Linux setting does the same thing as the macOS setting.

Please do open a bug if you find the Linux behavior is inconsistent with macOS.
