### ISSUE TITLE
Mesa OpenGL incompatible with kernel (UABI mismatch)

### ISSUE THREAD

**Issue by slipher** [AsahiLinux/linux#339]
This is a problem that I have already resolved, but I will describe it here in case somebody else hits it or there is something wrong with the package management.

Today I installed Asahi Linux and upgraded all the packages with `sudo dnf upgrade` (perhaps the latter was a bad idea?). Upon starting an SDL- and OpenGL-based app, it did not manage to use the GPU and got downgraded to llvmpipe. The following messages were seen in the terminal:

```
UABI mismatch: Kernel 10010, Mesa 10011
libEGL warning: egl: failed to create dri2 screen
```

I managed to fix this by downgrading the Mesa package. (Originally I had a 24.3.0.)
```
sudo dnf install mesa-libEGL-devel-24.1.0~asahipre20240228-2.fc40
```

**Comment by jannau** [comment]
This is most likely caused by upgrading the kernel and mesa without reboot. After the next boot you will hit the reverse problem. A reboot is recommended after mesa updates. Gnome Software / Discover or `dnf offline-upgrade` would achieve this by default.

**Comment by slipher** [comment]
Ah I didn't realize `dnf upgrade` could cause the kernel to be updated.
