### ISSUE TITLE
[QUESTION] Upstream Linux kernel changes after stable release

### ISSUE THREAD

**Issue by redradist** [AsahiLinux/linux#343]
Do you plan to upstream Linux kernel changes after stable release ?

**Comment by GuillaumeDIDIER** [comment]
They are already upstreaming things, even though it is an uphill battle.

The plan is for Asahi to eventually contain nothing ! (I wouldn't be surprised if they eventually end up carrying only the patches for the newest apple devices for short periods of time after the release of the device).

We are however not at that point yet, even though a non-negligible amount of work is already upstream.

**Comment by alyssarosenzweig** [comment]
Guillaume is correct
