### ISSUE TITLE
journalctl logs dissappearing

### ISSUE THREAD

**Issue by ericcurtin** [AsahiLinux/linux#35]
Some of my journalctl logs are going missing when I reboot, I am using this:

https://github.com/leifliddy/asahi-fedora-builder

with a realtime kernel:

https://github.com/ericcurtin/linux

with these config options:

https://github.com/ericcurtin/linux/blob/asahilinux-linux-rt-devel/config-m1.txt

Struggling to figure out why. I'm using a Mac Mini M1

**Comment by marcan** [comment]
Unlikely to be a kernel issue, unless it has to do with the machine not shutting down properly (including clean NVMe shutdown), but that should be working fine...

**Comment by ericcurtin** [comment]
I'm gonna close this, must investigate further since it's hard to pinpoint where in the stack this is. Thank's for the tips though
