### ISSUE TITLE
 hyprland's explicit_sync option breaks the honeykrisp vulkan driver

### ISSUE THREAD

**Issue by nerdyinu** [AsahiLinux/linux#353]
any gpu accelerated app which uses vulkan crashes. (zed, wezterm) with hyprland's explicit sync option turned on

to reproduce it in wezterm, 
first set explicit_sync=2 in hyprland config,
and set front_end = "WebGpu" 
and preferred_adapter to use the vulkan driver. 

here is the crash log when launching wezterm.

```
➜ wezterm [11:52:24]

wp_linux_drm_syncobj_timeline_v1#57: error 1: Timeline failed importing

11:52:28.178 ERROR wgpu_hal::vulkan::adapter > get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR

11:52:28.178 ERROR wgpu_hal::vulkan::adapter > get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR

11:52:28.179 ERROR env_bootstrap > panic at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18 - !?

0: <unknown>

1: <unknown>

2: <unknown>

3: <unknown>

4: <unknown>

5: <unknown>

6: <unknown>

7: <unknown>

8: <unknown>

9: <unknown>

10: <unknown>

11: <unknown>

12: <unknown>

13: <unknown>

14: <unknown>

15: <unknown>

16: <unknown>

17: <unknown>

18: <unknown>

19: <unknown>

20: <unknown>

21: <unknown>

22: <unknown>

23: <unknown>

24: <unknown>

25: <unknown>

26: __libc_start_call_main

27: __libc_start_main@@GLIBC_2.34

28: <unknown>

thread 'main' panicked at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18:

Error in Surface::configure: Validation Error

Caused by:

Requested format Bgra8UnormSrgb is not in list of supported formats: []

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/thread/local.rs:260:26:

thread panicked while processing panic. aborting.

Error: nu::shell::core_dumped

× External command core dumped

╭─[entry #1:1:1]

1 │ wezterm

· ───┬───

· ╰── core dumped with SIGABRT (6)

╰────

```

**Comment by marcan** [comment]
Tested the Wezterm COPR build on F41 with:

    WAYLAND_DEBUG=1 mutter --nested -- wezterm --config front_end=\"WebGpu\" 2>&1 | grep -i sync

The output confirms `wp_linux_drm_syncobj_timeline_v1` is being used, and it works. Ctrl-Shift-L shows the GPU backend is Vulkan on Honeykrisp. Therefore, this is most likely a Hyprland bug.

**Comment by vaxerski** [comment]
split render node issue perhaps?

This fails:
https://github.com/hyprwm/Hyprland/blob/5f7ad767dbf0bac9ddd6bf6c825fb9ed7921308a/src/helpers/sync/SyncTimeline.cpp#L26-L29

**Comment by marcan** [comment]
On December 23, 2024 11:51:44 AM GMT+01:00, Vaxry ***@***.***> wrote:
>split render node issue perhaps?
>
>This fails:
>https://github.com/hyprwm/Hyprland/blob/5f7ad767dbf0bac9ddd6bf6c825fb9ed7921308a/src/helpers/sync/SyncTimeline.cpp#L26-L29
>

Almost certainly. Only render nodes have syncobj support, display only nodes do not.
-- Hector

**Comment by vaxerski** [comment]
Gotcha. That's probably it then, thanks.

Travelling back home for xmas today might be a bit busy but I'll try to fix this once I have a moment and dont forget.

**Comment by marcan** [comment]
Closing since I assume this is being tracked on the hyprland side now.

**Comment by vaxerski** [comment]
yup, for those interested, ref https://github.com/hyprwm/Hyprland/issues/8158
