### ISSUE TITLE
Building and Installing Kernel Modules in Asahi

### ISSUE THREAD

**Issue by adamtuby** [AsahiLinux/linux#37]
Hey, was just wondering (I hope this is the right place to ask this), is there support for building and installing kernel modules? I tried installing the standard `linux-headers` for aarch64 and working with that, but as expected, it didn't really go well (compiling went fine, but installing it failed with `invalid module format`). 

Thanks in advance for any type of help/guidance!
Adam

**Comment by sdirkwinkel** [comment]
Kernel packages on arch are usually kernelname-headers. Since the asahi kernel is linux-asahi you'd need linux-asahi-headers.

If that doesn't work the right place to ask might be on irc or there: https://github.com/AsahiLinux/PKGBUILDs/issues

**Comment by adamtuby** [comment]
> Kernel packages on arch are usually kernelname-headers. Since the asahi kernel is linux-asahi you'd need linux-asahi-headers.
> 
> If that doesn't work the right place to ask might be on irc or there: https://github.com/AsahiLinux/PKGBUILDs/issues

Thank you! It was exactly that.
Haven't experienced much with arch yet to know that, thank you again.
