### ISSUE TITLE
Perf stat not functioning

### ISSUE THREAD

**Issue by tomhepworth** [AsahiLinux/linux#38]
If I use perf stat the cycles and instruction events show `<not counted>` about 99% of the time. Has anyone else had any luck with perf? Could something perhaps be wrong with the driver? I am on an M1 Mac Mini. 

`perf stat -e cycles,instructions ls` 
```
     <not counted>      cycles:u                                                      (0.00%)
     <not counted>      instructions:u                                                (0.00%)

       0.000535494 seconds time elapsed

       0.000555000 seconds user
       0.000000000 seconds sys

```

**Comment by adamtuby** [comment]
Hey, the performance counters on the M1 architecture are pretty much disabled considering all of the available performance counters are EL1 privilege and up. I'm currently trying to write a kernel module to expose those performance counters to userspace. Currently, I'm failing to do so with asahilinux, but able to do so on macOS.

update:
It seems as if asahi didn't expose the system registers of the M1 through the hypervisor. I'm unable to read (nor edit) very simple EL0 registers such as `CNTPCT_EL0` on `asahi` but I'm able to do so on `macOS`.

**Comment by tomhepworth** [comment]
I have been in to the IRC rooms and got help to solve my problem. Specifying a core will yield results.

I am now using a command like:

 `sudo taskset --cpu-list 0 perf stat -C 0 -e apple_firestorm_pmu/cycles/ -e apple_icestorm_pmu/cycles/ -e apple_firestorm_pmu/instructions/ -e apple_icestorm_pmu/instructions/ awk 'BEGIN{for(i=0;i<1000000;i++){}}'`
 
 to profile a program on a specific core.
