### ISSUE TITLE
Unable To Read System Registers on AsahiLinux

### ISSUE THREAD

**Issue by adamtuby** [AsahiLinux/linux#39]
Hey, I've tried writing a very basic kernel module for `asahi` that exposes EL1 system registers to userspace, but it always fails with reading the system registers as 0. I then found out that even EL0 registers such as `CNTPCT_EL0` aren't accessible from EL0, while on the other hand, the preinstalled bare metal `macOS` on my mac does expose those system registers. Is there some kind of barrier between `asahi` and the hardware?

Thanks in advance for any type of help/guidance,
Adam.

**Comment by marcan** [comment]
There is nothing special involved here, other than the Linux kernel not configuring CNTPCT_EL0 as readable by userspace. EL1 system registers are readable from the kernel as you would expect. See `CNTKCTL_EL1` for the userspace access config.
