### ISSUE TITLE
Boot loop after updating packages

### ISSUE THREAD

**Issue by adamtheadmin** [AsahiLinux/linux#42]
After running `sudo pacman -Syu` My mac mini just boot loops until it reaches a recovery screen.

**Comment by adamtheadmin** [comment]
Turns out the culprit was my usb-c HDD. Switching to USB 3 temporarily fixes the issue.

**Comment by marcan** [comment]
This is probably the U-Boot LUN issue, which should be fixed now. Next time please file the issue in the correct repo (this is for the kernel).
