### ISSUE TITLE
So sorry if I'm asking this in the wrong place, i just don't know on which repo i should ask on

### ISSUE THREAD

**Issue by itaysharir** [AsahiLinux/linux#45]
Is there an estimated time for when speaker and mic are going to be supported? It's the only thing stopping me from switching to Asahi. Thanks

**Comment by lomichael** [comment]
I believe [this](https://github.com/AsahiLinux/docs/wiki/Feature-Support) is where they try to keep updates on feature support. Or maybe try asking on IRC?

**Comment by Willmish** [comment]
Mic i am not sure, regarding speakers, like @lomichael mentioned more info on that page (full explanation here: https://github.com/AsahiLinux/docs/wiki/Feature-Support#speakers)

TLDR: speaker drivers are in place, but disabled to not blow them (need some safety features added to limit max signal)

**Comment by marcan** [comment]
Please do not file GitHub issues for random questions or not-yet-supported hardware, and please do not ask for ETAs. If everyone does that, it just waste everyone's time. Hardware support will come when it's ready.
