### ISSUE TITLE
[Feature Request] Full featured Internal Screen of MBP

### ISSUE THREAD

**Issue by levihuayuzhang** [AsahiLinux/linux#69]
Thanks for the great works! 
The 4K resolution and accelerated Gnome are awesome!🎉

And I'm wondering if we can do following for the Internal Display of MBP:

1. P3-1600nits Color profile
2. Linear adjustment for back light control (and I found the current display back light seems not as 'bright' as it in MacOS(up to 500nits in normal display mode))
3. 120hz support
4. Pro-display (1~120hz dynamic adjustment)
5. Full HDR support

**Comment by jannau** [comment]
Please do not fill feature requests for obvious things.
