### ISSUE TITLE
When I boot my system, sometimes it will boot, and sometimes it will not, causing my system to restart and boot into macOS.

### ISSUE THREAD

**Issue by SamilKaraduman** [AsahiLinux/linux#75]
I've decided to install the new OpenGL GPU update but after I reboot, my Asahi install wont boot; I've selected Arch from grub but after that it gets stuck on the screen after that and reboots. What can I do to troubleshoot this issue? Thanks. 

Host: MacBook Air (M1, 2020)
OS: Arch Linux ARM

**Comment by retromuz** [comment]
Did you compile the source and update the kernel?

**Comment by SamilKaraduman** [comment]
> 

just used the update guide using this link: https://asahilinux.org/2022/12/gpu-drivers-now-in-asahi-linux/

**Comment by SamilKaraduman** [comment]
Update: My system will now boot, (after multiple reboots) however I had this problem before I even installed the GPU update. Sometimes it will work, and sometimes it will not.

**Comment by marcan** [comment]
Please attach an `asahi-diagnose` log from a boot that worked.

**Comment by SamilKaraduman** [comment]
> Please attach an `asahi-diagnose` log from a boot that worked.

[asahi-diagnose-20221209-153446.txt](https://github.com/AsahiLinux/linux/files/10197977/asahi-diagnose-20221209-153446.txt)

**Comment by marcan** [comment]
Hmm, I don't see anything weird in there. Can you describe exactly what happens when the machine fails to boot? A video might be nice too.
