### ISSUE TITLE
plasma wayland won't launch 

### ISSUE THREAD

**Issue by todthetoad** [AsahiLinux/linux#77]
I just installed the new gpu driver and installed plasma wayland as recommended from the wiki but it won't launch

**Comment by monomycelium** [comment]
How did you install the new driver? Just curious.

---

Edit: Never mind, I just found out about the new blog post!

**Comment by lkvrsfld** [comment]
What stub partition version did you choose? It seems to only work with the recommended one (which is the lower one, i think 12.2)
Had the same issue. Installed asahi again, with the lower macos stub version, and now it works fine.

**Comment by marcan** [comment]
The higher stub versions are only shown in expert mode. They are for development only. They are not supported. If you use expert mode and pick the wrong options, you are on your own.

Please attach an `asahi-diagnose` log.
