### ISSUE TITLE
Plasma (wayland) won't launch with GPU drivers and asahi-edge kernel

### ISSUE THREAD

**Issue by BarisUlas** [AsahiLinux/linux#81]
I've followed the guide and installed the `mesa-asahi-edge` and `asahi-edge` kernel. When I reboot the asahi linux, and choose `Wayland` to login, I only get a blinking blank screen and it goes back to the login screen after about three seconds. My macOS version is 12.6.1, and I installed asahi-linux about 3 months ago *without* enabling the expert mode. You can find the `asahi-diagnose` file below. Please let me know if you need any more details. Thanks!
[asahi-diagnose-20221207-110359.txt](https://github.com/AsahiLinux/linux/files/10193389/asahi-diagnose-20221207-110359.txt)

**Comment by marcan** [comment]
Please attach /boot/efi/asahi/installer.log.

**Comment by BarisUlas** [comment]
[installer.log](https://github.com/AsahiLinux/linux/files/10195294/installer.log)

**Comment by marcan** [comment]
> 08-05 12:12 root         INFO     MSG: By default, this installer will hide certain advanced options that
> 08-05 12:12 root         INFO     MSG: are only useful for developers. You can enable expert mode to show them.
> 08-05 12:12 root         INFO     MSG: [1;37m»[1;36m Enable expert mode? (y/N): [m
> 08-05 12:12 root         INFO     INPUT: 'y'

So you enabled expert mode.

> 08-05 12:20 root         INFO     MSG: Choose the macOS version to use for boot firmware:
> 08-05 12:20 root         INFO     MSG: (If unsure, just press enter)

You were then prompted to choose a firmware, and told that you should press enter if unsure.

> 08-05 12:20 root         INFO     MSG:   [1m1[22m: 12.4[m
> 08-05 12:20 root         INFO     MSG:   [1m2[22m: 12.3[m
> 08-05 12:20 root         INFO     MSG: [1;37m»[1;36m Version (2): [m
> 08-05 12:20 root         INFO     INPUT: '1'
> 08-05 12:20 root         INFO     MSG: Using macOS 12.4 for OS firmware

You then explicitly chose 12.4, which was not the default. You were sure you wanted 12.4, you got 12.4, and you now have an unsupported setup.

Closing.
