### ISSUE TITLE
Keyboard and mouse not working after boot

### ISSUE THREAD

**Issue by crab2313** [AsahiLinux/linux#82]
```
spi-hid-apple-of spi0.0: waiting for device info failed: -19
```

This issue can be fixed by: 
```
modprobe -r spi-hid-apple-of && modprobe spi-hid-apple-of
```

https://www.reddit.com/r/AsahiLinux/comments/z9zx5g/keyboard_and_mouse_not_working_after_boot/

**Comment by crab2313** [comment]
[asahi-diagnose-20221210-140157.txt](https://github.com/AsahiLinux/linux/files/10199301/asahi-diagnose-20221210-140157.txt)

**Comment by crab2313** [comment]
Keyboard is working in uboot and grub.

**Comment by ehntoo** [comment]
I have seen this issue on my 14" M1 Max MBP as well, and I noticed some interesting behavior. After the system booted to the login greeter, I mashed a number of keys on the keyboard. I then shut the system down using the power button/touch ID, then powered it back on via the same button. At u-boot entry, the keys I'd mashed on the previous boot halted the u-boot sequence and showed up in the u-boot prompt.

**Comment by apple-corps** [comment]
Looks like this describes removing and reloading the a kernel module. Not sure if this is suggesting to reload the module from a running linux session or if it resolves the issue completely.  

It sounds like a work-around for the current boot session and not a long term fix. But perhaps the module wasn't installed properly?

https://www.reddit.com/r/AsahiLinux/comments/10qm9pq/comment/j6zo9w5/?utm_source=share&utm_medium=web2x&context=3

**Comment by Droppix** [comment]
same issue on mbp 16 (m1), after upgrade packman

**Comment by jannau** [comment]
> same issue on mbp 16 (m1), after upgrade packman

Different issue, should be fixed by another `pacman -Syu` which updates libinput to 1.23.0-1

**Comment by marcan** [comment]
As far as I know all the touchpad craziness is (finally) fixed these days. Please report if you still have issues.
