### ISSUE TITLE
Gnome doesn't boot into Wayland 

### ISSUE THREAD

**Issue by levihuayuzhang** [AsahiLinux/linux#83]
Kernel: linux-asahi-edge
Mesa: mesa-edge

Hi, I'm using the `edge` version of kernel and mesa. But even I set Enable-Wayland to `True` and default session point to Gnome-Wayland, the GDM will boot into X11 but not Wayland.

At the fresh boot, the GDM would show only `Gnome` session and `Gnome-legacy` (which should be Wayland session), and the `Gnome` is selected by default. But after entering the DE, the sessio is actually running under X11.

After these, log out -> re-enter again, the session would be Wayland. (And in the process, the GDM would show X11 sessions under Wayland sessions in the right down menu in GDM)

I'm wondering if the boot process not load support for Wayland or somthing?

**Comment by marcan** [comment]
This is not a kernel issue. Sorry, we don't support Gnome/GDM, you'll have to figure that out yourself.

**Comment by levihuayuzhang** [comment]
Hi, I found a solution for Nvidia but not Asahi:
<https://bbs.archlinux.org/viewtopic.php?id=279871>

And in Arch Linux WiKi <https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting>, I found that nvidia driver use `nvidia_drm.modeset=1` to enable Wayland support by early loading the DRM modules.

But I think the parameter like `asahi_drm.modeset=1` or `apple_drm.modeset=1` not working.

Besides, I've tried to add `asahi`, `appledrm`, `apple_dcp` to `/etc/mkinitcpio.conf` to generate new initramfs to early load the modules. But the `mkinitcpio` promopt Errors like:
```sh
==> ERROR: module not found: `drm_dma_helper'
==> ERROR: module not found: `asahi'
==> ERROR: module not found: `apple_piodma'
==> ERROR: module not found: `appledrm'
```
Thus, I'm wondering if there any way we can use kernel parameter to early load DRM module for apple(asahi) OR any way to add related modules to initramfs? (so we can have Wayland support at fresh boot?) (and this may improve `default` experience, because the Wayland seems works much better than X11 in `mesa-edge` and `asahi-linux-edge` for now)

**Comment by levihuayuzhang** [comment]
Ok, I find the solution (just add DRM support in initramfs):
1. Edit the `mkinitcpio` HOOK file `asahi` using `vim /usr/lib/initcpio/install/asahi`:
2. add following content:
```sh
# For DRM
    map add_module drm_dma_helper? asahi? apple_piodma? appledrm? \
	 apple_dcp?  panel-simple? virtio-gpu? gpu-sched?
```
3. generate a new initramfs image for `asahi-linux-edge`:
```sh
mkinitcpio -p linux-asahi-edge
```
4. The Gnome use Wayland by default, but if you want to ensure, edit `vim /etc/gdm/custom.conf`:
```sh
[daemon]
WaylandEnable=true
DefaultSession=gnome-wayland.desktop
```
5. Fresh reboot, then then GPU accelerated Wayland Gnome would be works (without log out). 
6. (No need to modify grub settings or use kernel parameter)

I'm wondering if the DRM features become stable enough (in the future or maybe now?), maybe we can add the DRM modules to initramfs to improve `default` experience (Cause the Wayland seems works better than X11 with Asahi for now)?
