### ISSUE TITLE
Touch pad on M1 Max (16` MBP) lose randomly at the corner or edge

### ISSUE THREAD

**Issue by levihuayuzhang** [AsahiLinux/linux#84]
Kernel: linux-asahi-edge
Mesa: mesa-edge

The touch pad seems can't detact touching at the edge at top, right and left. But the button edge and center part works fine.

**Comment by jannau** [comment]
this sounds like it's libinput's [palm detection](https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html#palm-exclusion-zones) and not a kernel issue
