### ISSUE TITLE
Screen flashing in X11

### ISSUE THREAD

**Issue by levihuayuzhang** [AsahiLinux/linux#85]
Kernel: edge
Mesa: edge
session: X11
DE: Gnome

When I filling info for WIFI IN Gnome setting panel, the screen start fast flashing (from nolmar light level to lower, but not completly blank).
And I can hear some current sound from power adapter at same time.

After filling, the screen back to normal and the sound disapear.

I think it not just display issue but also envolve some power issue?

**Comment by marcan** [comment]
Please report graphical issues in #72.
