### ISSUE TITLE
[Feature Request] Touch Pad profile improving.

### ISSUE THREAD

**Issue by levihuayuzhang** [AsahiLinux/linux#86]
The current default profile of Touch pad is usable. But maybe we can make it more handy like it was in MacOS?

**Comment by marcan** [comment]
This is not a kernel issue. The kernel touchpad driver reports all multitouch events to userspace, and the rest of the handling is done by libinput and desktop compositors.

If you find specific configuration options we can add that would help the default experience, feel free to suggest them as an issue on the `PKGBUILDs` repository. But if you want new features, that's something to report upstream in libinput or your desktop environment.

Keep in mind that the goal of Asahi Linux is to make Linux work *as well as it does on other platforms* on Macs. We can't make Linux work like macOS and have all of its features/UX. That's for individual upstream projects to work on. We do care about configuration/defaults (like how I just submitted a PR to libinput to default to natural scrolling for all desktops on Apple touchpads), but feature development belongs upstream.

**Comment by levihuayuzhang** [comment]
I see. 
And thanks for the great work of Asahi Dev Team.
