### ISSUE TITLE
Colour temperature cannot change

### ISSUE THREAD

**Issue by Consistos** [AsahiLinux/linux#91]
Using `asahi-edge` on a M2, on both Wayland and X11, KDE's night colours, gammastep (Wayland) and redshift (X11) does not change the colour temperature.

`gammastep -v`:

```Notice: Solar elevations: > 3.0 (Day), < -6.0 (Nuit)
Notice: Temperatures: 6500K (Day), 4500K (Nuit)
Notice: Brightness: 1.00:1.00
Notice: Gamma (Day): 1.000, 1.000, 1.000
Notice: Gamma (Nuit): 1.000, 1.000, 1.000
Error: Could not control gamma, exiting.
Error: Failed to start adjustment method: wayland
```

 `redshift -v` (X11, sorry it's in french):
```Essai du fournisseur de localisation « geoclue2 »...
Utilisation du fournisseur « geoclue2 ».
Élévations solaires : jour au-dessus de 3.0, nuit en-dessous de -6.0
Températures : 6500K le jour, 4500K la nuit
Luminosité : 1.00:1.00
Gamma (Journée) : 1.000, 1.000, 1.000
Gamma (Nuit) : 1.000, 1.000, 1.000
Utilisation de la méthode « randr ».
En attente de localisation initiale...
Localisation : 47.46°N,0.55°O
Température de couleur : 6500K
Luminosité : 1.00
État : Activé
Période : Nuit
Température de couleur : 4500K``

**Comment by hoshinolina** [comment]
This is not implemented yet in the DCP driver, it is not a bug.

**Comment by blackbookpro** [comment]
Ok, thanks! And thanks for your awesome work on this great project! I'm using Asahi already as my daily driver and it's been a great ride so far! :) 
Is there any rough expectation on when it might be implemented? Cause night color really makes life easier..

**Comment by DavidBuchanan314** [comment]
I believe this PR is related https://github.com/AsahiLinux/linux/pull/119

**Comment by jannau** [comment]
Yes, with #119 Night Color in kwin 5.27.3 and later will work. Kwin is to my knowledge the only software which can use DRM/KMS' color transformation matrix (CTM) for the color temperature adjustments.
Gamma adjustment can be supported but requires figuring out how it works in detail.

**Comment by marcan** [comment]
This works now on KDE. If you want support with other compositors, please ask upstream to support CTM. Gamma table adjustment will probably be supported in the future, but there is no ETA.
