### ISSUE TITLE
Tilde key mapped to backslash

### ISSUE THREAD

**Issue by tobhe** [AsahiLinux/linux#93]
On my ansi us keyboard both tilde and backslash map to keycode 51.
The offending commit seems to be 55b3917023a3f89eb6be874b401ea010771e2a90

**Comment by jannau** [comment]
Please append the output of `asahi-diagnose` and `cat /sys/module/hid_apple/drivers/hid:apple/*/country`. Based on the offending commit it looks like the hid country assignment is not correct for `us-ansi` keyboards on M2 based devices.

**Comment by tobhe** [comment]
Indeed, it looks like that might be the reason. I will investigate further, meanwhile here are the command outputs you requested:

$ cat /sys/module/hid_apple/drivers/hid:apple/*/country
0d

asahi-diagnose output is here: https://tobhe.de/files/asahi-diagnose-20221216-134116.txt

**Comment by tobhe** [comment]
Adding debug prints shows that `dchid->device_id.keyboard_type == 7` which means we set country to `HID_COUNTRY_INTERNATIONAL_ISO == 13` on my ANSI keyboard. We might need to find someone with a M2 Air with an actual ISO keyboard to see what type they are getting.

**Comment by cyrinux** [comment]
Hi, I got 0d too on m2 air azerty keyboard

**Comment by marcan** [comment]
Ugh, I hope we don't have to go digging this out of the ADT layout after all.

I'm adding a debug print of the raw keyboard type, hopefully we can figure it out that way...

**Comment by tobhe** [comment]
Closing because this seems to be resolved with the last kernel update. Thanks everyone :)
