### ISSUE TITLE
macos Ashai Linux - Brightness only fill/min using F1/F2

### ISSUE THREAD

**Issue by AlexisBallo2** [AsahiLinux/linux#98]
The macos brightness keys only alternate between min and max brightness. F1 brings to full darkness, and F2 brings to maximum brightness.

**Comment by h0m3** [comment]
Brigthness is only implemented on asahi-edge, beware that this driver is still Alpha and may bring other issues.

For now what Asahi does is literally kill the power from the LCD backlight, so we can turn the screen off, but theres no middle ground. Macbooks will remember your backlight settings from macOS on Asahi so you can setup a reasonable backlight level on macos and keep that on Asahi for now.

Check out this blog post to know more about it: https://asahilinux.org/2022/11/november-2022-report/

marcan wrote two sections about the backlight ;)

**Comment by marcan** [comment]
Working as intended, see the above link for how to get the DCP driver.
