### ISSUE TITLE
Asahi installed on external HDD does not boot

### ISSUE THREAD

**Issue by playXE** [AsahiLinux/linux#99]
It freezes when Asahi logo shows up

**Comment by jannau** [comment]
How did you install Asahi Linux on an external HDD? The installer does not support that. It has the option to install `m1n1` in proxy mode onto an external storage device. This is only visible if you chose export mode which comes with following message:

> By default, this installer will hide certain advanced options that
> are only useful for Asahi Linux developers. You can enable expert mode
> to show them. Do not enable this unless you know what you are doing.
> Please do not file bugs if things go wrong in expert mode.

**Comment by marcan** [comment]
This is not supported, so not a bug.
